// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/nullable"
	"github.com/oapi-codegen/runtime"
)

const (
	TurnstileTokenScopes = "TurnstileToken.Scopes"
)

// Defines values for AgentId.
const (
	AgentIdHistorian AgentId = "historian"
	AgentIdHumanist  AgentId = "humanist"
	AgentIdStrict    AgentId = "strict"
)

// Valid indicates whether the value is a known member of the AgentId enum.
func (e AgentId) Valid() bool {
	switch e {
	case AgentIdHistorian:
		return true
	case AgentIdHumanist:
		return true
	case AgentIdStrict:
		return true
	default:
		return false
	}
}

// Defines values for AgentSenderType.
const (
	Agent AgentSenderType = "agent"
)

// Valid indicates whether the value is a known member of the AgentSenderType enum.
func (e AgentSenderType) Valid() bool {
	switch e {
	case Agent:
		return true
	default:
		return false
	}
}

// Defines values for CouncilCaseType.
const (
	Corruption      CouncilCaseType = "corruption"
	GeneralCriminal CouncilCaseType = "general_criminal"
	Narcotics       CouncilCaseType = "narcotics"
	Other           CouncilCaseType = "other"
)

// Valid indicates whether the value is a known member of the CouncilCaseType enum.
func (e CouncilCaseType) Valid() bool {
	switch e {
	case Corruption:
		return true
	case GeneralCriminal:
		return true
	case Narcotics:
		return true
	case Other:
		return true
	default:
		return false
	}
}

// Defines values for CreateSessionStreamEventType.
const (
	CreateSessionStreamEventTypeAgentComplete   CreateSessionStreamEventType = "agent_complete"
	CreateSessionStreamEventTypeAgentStart      CreateSessionStreamEventType = "agent_start"
	CreateSessionStreamEventTypeChunk           CreateSessionStreamEventType = "chunk"
	CreateSessionStreamEventTypeError           CreateSessionStreamEventType = "error"
	CreateSessionStreamEventTypeSessionComplete CreateSessionStreamEventType = "session_complete"
	CreateSessionStreamEventTypeSessionCreated  CreateSessionStreamEventType = "session_created"
	CreateSessionStreamEventTypeStatus          CreateSessionStreamEventType = "status"
)

// Valid indicates whether the value is a known member of the CreateSessionStreamEventType enum.
func (e CreateSessionStreamEventType) Valid() bool {
	switch e {
	case CreateSessionStreamEventTypeAgentComplete:
		return true
	case CreateSessionStreamEventTypeAgentStart:
		return true
	case CreateSessionStreamEventTypeChunk:
		return true
	case CreateSessionStreamEventTypeError:
		return true
	case CreateSessionStreamEventTypeSessionComplete:
		return true
	case CreateSessionStreamEventTypeSessionCreated:
		return true
	case CreateSessionStreamEventTypeStatus:
		return true
	default:
		return false
	}
}

// Defines values for DeliberationPhase.
const (
	Convergence DeliberationPhase = "convergence"
	Debate      DeliberationPhase = "debate"
	Legacy      DeliberationPhase = "legacy"
	Opening     DeliberationPhase = "opening"
	Summary     DeliberationPhase = "summary"
)

// Valid indicates whether the value is a known member of the DeliberationPhase enum.
func (e DeliberationPhase) Valid() bool {
	switch e {
	case Convergence:
		return true
	case Debate:
		return true
	case Legacy:
		return true
	case Opening:
		return true
	case Summary:
		return true
	default:
		return false
	}
}

// Defines values for InputType.
const (
	ExtractionId InputType = "extraction_id"
	TextSummary  InputType = "text_summary"
)

// Valid indicates whether the value is a known member of the InputType enum.
func (e InputType) Valid() bool {
	switch e {
	case ExtractionId:
		return true
	case TextSummary:
		return true
	default:
		return false
	}
}

// Defines values for NarcoticsIntent.
const (
	Distribution NarcoticsIntent = "distribution"
	PersonalUse  NarcoticsIntent = "personal_use"
	Unknown      NarcoticsIntent = "unknown"
)

// Valid indicates whether the value is a known member of the NarcoticsIntent enum.
func (e NarcoticsIntent) Valid() bool {
	switch e {
	case Distribution:
		return true
	case PersonalUse:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for PositionStance.
const (
	Agree      PositionStance = "agree"
	Disagree   PositionStance = "disagree"
	NoPosition PositionStance = "no_position"
	Partial    PositionStance = "partial"
)

// Valid indicates whether the value is a known member of the PositionStance enum.
func (e PositionStance) Valid() bool {
	switch e {
	case Agree:
		return true
	case Disagree:
		return true
	case NoPosition:
		return true
	case Partial:
		return true
	default:
		return false
	}
}

// Defines values for SendMessageRequestTargetAgent.
const (
	SendMessageRequestTargetAgentAll       SendMessageRequestTargetAgent = "all"
	SendMessageRequestTargetAgentHistorian SendMessageRequestTargetAgent = "historian"
	SendMessageRequestTargetAgentHumanis   SendMessageRequestTargetAgent = "humanis"
	SendMessageRequestTargetAgentHumanist  SendMessageRequestTargetAgent = "humanist"
	SendMessageRequestTargetAgentLegalis   SendMessageRequestTargetAgent = "legalis"
	SendMessageRequestTargetAgentSejarawan SendMessageRequestTargetAgent = "sejarawan"
	SendMessageRequestTargetAgentStrict    SendMessageRequestTargetAgent = "strict"
)

// Valid indicates whether the value is a known member of the SendMessageRequestTargetAgent enum.
func (e SendMessageRequestTargetAgent) Valid() bool {
	switch e {
	case SendMessageRequestTargetAgentAll:
		return true
	case SendMessageRequestTargetAgentHistorian:
		return true
	case SendMessageRequestTargetAgentHumanis:
		return true
	case SendMessageRequestTargetAgentHumanist:
		return true
	case SendMessageRequestTargetAgentLegalis:
		return true
	case SendMessageRequestTargetAgentSejarawan:
		return true
	case SendMessageRequestTargetAgentStrict:
		return true
	default:
		return false
	}
}

// Defines values for SessionStatus.
const (
	SessionStatusActive    SessionStatus = "active"
	SessionStatusArchived  SessionStatus = "archived"
	SessionStatusConcluded SessionStatus = "concluded"
)

// Valid indicates whether the value is a known member of the SessionStatus enum.
func (e SessionStatus) Valid() bool {
	switch e {
	case SessionStatusActive:
		return true
	case SessionStatusArchived:
		return true
	case SessionStatusConcluded:
		return true
	default:
		return false
	}
}

// Defines values for StreamEventType.
const (
	StreamEventTypeAgentComplete         StreamEventType = "agent_complete"
	StreamEventTypeAgentError            StreamEventType = "agent_error"
	StreamEventTypeAgentStart            StreamEventType = "agent_start"
	StreamEventTypeChunk                 StreamEventType = "chunk"
	StreamEventTypeConvergenceSuggestion StreamEventType = "convergence_suggestion"
	StreamEventTypeDeliberationComplete  StreamEventType = "deliberation_complete"
	StreamEventTypePhaseTransition       StreamEventType = "phase_transition"
	StreamEventTypeSummaryReady          StreamEventType = "summary_ready"
	StreamEventTypeUserMessage           StreamEventType = "user_message"
)

// Valid indicates whether the value is a known member of the StreamEventType enum.
func (e StreamEventType) Valid() bool {
	switch e {
	case StreamEventTypeAgentComplete:
		return true
	case StreamEventTypeAgentError:
		return true
	case StreamEventTypeAgentStart:
		return true
	case StreamEventTypeChunk:
		return true
	case StreamEventTypeConvergenceSuggestion:
		return true
	case StreamEventTypeDeliberationComplete:
		return true
	case StreamEventTypePhaseTransition:
		return true
	case StreamEventTypeSummaryReady:
		return true
	case StreamEventTypeUserMessage:
		return true
	default:
		return false
	}
}

// Defines values for StreamMessageRequestTargetAgent.
const (
	All       StreamMessageRequestTargetAgent = "all"
	Historian StreamMessageRequestTargetAgent = "historian"
	Humanis   StreamMessageRequestTargetAgent = "humanis"
	Humanist  StreamMessageRequestTargetAgent = "humanist"
	Legalis   StreamMessageRequestTargetAgent = "legalis"
	Sejarawan StreamMessageRequestTargetAgent = "sejarawan"
	Strict    StreamMessageRequestTargetAgent = "strict"
)

// Valid indicates whether the value is a known member of the StreamMessageRequestTargetAgent enum.
func (e StreamMessageRequestTargetAgent) Valid() bool {
	switch e {
	case All:
		return true
	case Historian:
		return true
	case Humanis:
		return true
	case Humanist:
		return true
	case Legalis:
		return true
	case Sejarawan:
		return true
	case Strict:
		return true
	default:
		return false
	}
}

// Defines values for SystemSenderType.
const (
	System SystemSenderType = "system"
)

// Valid indicates whether the value is a known member of the SystemSenderType enum.
func (e SystemSenderType) Valid() bool {
	switch e {
	case System:
		return true
	default:
		return false
	}
}

// Defines values for UserSenderType.
const (
	User UserSenderType = "user"
)

// Valid indicates whether the value is a known member of the UserSenderType enum.
func (e UserSenderType) Valid() bool {
	switch e {
	case User:
		return true
	default:
		return false
	}
}

// Defines values for VerdictDecision.
const (
	Acquitted VerdictDecision = "acquitted"
	Guilty    VerdictDecision = "guilty"
	NotGuilty VerdictDecision = "not_guilty"
)

// Valid indicates whether the value is a known member of the VerdictDecision enum.
func (e VerdictDecision) Valid() bool {
	switch e {
	case Acquitted:
		return true
	case Guilty:
		return true
	case NotGuilty:
		return true
	default:
		return false
	}
}

// Defines values for ListCouncilSessionsParamsStatus.
const (
	ListCouncilSessionsParamsStatusActive    ListCouncilSessionsParamsStatus = "active"
	ListCouncilSessionsParamsStatusArchived  ListCouncilSessionsParamsStatus = "archived"
	ListCouncilSessionsParamsStatusConcluded ListCouncilSessionsParamsStatus = "concluded"
)

// Valid indicates whether the value is a known member of the ListCouncilSessionsParamsStatus enum.
func (e ListCouncilSessionsParamsStatus) Valid() bool {
	switch e {
	case ListCouncilSessionsParamsStatusActive:
		return true
	case ListCouncilSessionsParamsStatusArchived:
		return true
	case ListCouncilSessionsParamsStatusConcluded:
		return true
	default:
		return false
	}
}

// AgentId Identifiers for the judicial AI agents
type AgentId string

// AgentPosition An agent's position on a specific issue in the deliberation
type AgentPosition struct {
	// Issue The deliberation issue being discussed
	Issue string `json:"issue"`

	// ReasoningSummary 1-2 sentence summary of the agent's reasoning
	ReasoningSummary string `json:"reasoning_summary"`

	// RoundStated The round number when this position was stated
	RoundStated int `json:"round_stated"`

	// Stance An agent's stance on a deliberation issue
	Stance PositionStance `json:"stance"`
}

// AgentSender defines model for AgentSender.
type AgentSender struct {
	// AgentId Identifiers for the judicial AI agents
	AgentId AgentId         `json:"agent_id"`
	Type    AgentSenderType `json:"type"`
}

// AgentSenderType defines model for AgentSender.Type.
type AgentSenderType string

// AgreementMap Tracks agent positions and agreement across deliberation issues
type AgreementMap struct {
	// ConvergenceScore Proportion of issues with majority agreement (0.0-1.0)
	ConvergenceScore *float32 `json:"convergence_score,omitempty"`

	// Issues Map of issue_key to agent positions (agent_id -> AgentPosition)
	Issues *map[string]map[string]AgentPosition `json:"issues,omitempty"`

	// LastConvergenceCheck Round number of the last convergence check
	LastConvergenceCheck *int `json:"last_convergence_check,omitempty"`
	RegressionCount      *int `json:"regression_count,omitempty"`
	RoundCount           *int `json:"round_count,omitempty"`
}

// ApplicableLaw An applicable law reference
type ApplicableLaw struct {
	// Description Description of the law
	Description string `json:"description"`

	// HowItApplies How this law applies to the case
	HowItApplies string `json:"how_it_applies"`

	// LawReference Reference to the law (e.g., Article 2 UU 31/1999)
	LawReference string `json:"law_reference"`
}

// ArgumentPoint A single argument point in the legal opinion
type ArgumentPoint struct {
	// Argument Single bullet-point legal argument. ONE concise sentence stating
	// only the substantive legal point — no greetings, honorifics
	// ("Yang Mulia"), speaker self-references ("Saya berpendapat"), or
	// introductory framing. Suitable for direct rendering as a list
	// item. Maximum ~40 words.
	Argument string `json:"argument"`

	// SourceAgent Identifiers for the judicial AI agents
	SourceAgent AgentId `json:"source_agent"`

	// Strength Argument strength (strong, moderate, weak)
	Strength string `json:"strength"`

	// SupportingCases Cases supporting this argument
	SupportingCases *[]string `json:"supporting_cases,omitempty"`
}

// CaseInput Complete case input with raw and parsed data
type CaseInput struct {
	// InputType Type of case input
	InputType InputType `json:"input_type"`

	// ParsedCase Parsed and structured case information
	ParsedCase ParsedCaseInput `json:"parsed_case"`
	RawInput   string          `json:"raw_input"`
}

// CaseRecord A case record from the database
type CaseRecord struct {
	CaseNumber nullable.Nullable[string] `json:"case_number,omitempty"`

	// CaseType Types of legal cases
	CaseType               *CouncilCaseType                          `json:"case_type,omitempty"`
	CorruptionDetails      nullable.Nullable[map[string]interface{}] `json:"corruption_details,omitempty"`
	CourtName              nullable.Nullable[string]                 `json:"court_name,omitempty"`
	CourtType              nullable.Nullable[string]                 `json:"court_type,omitempty"`
	DecisionDate           nullable.Nullable[string]                 `json:"decision_date,omitempty"`
	DefendantAge           nullable.Nullable[int]                    `json:"defendant_age,omitempty"`
	DefendantFirstOffender nullable.Nullable[bool]                   `json:"defendant_first_offender,omitempty"`
	DefendantName          nullable.Nullable[string]                 `json:"defendant_name,omitempty"`
	ExtractionResult       nullable.Nullable[map[string]interface{}] `json:"extraction_result,omitempty"`
	Id                     *string                                   `json:"id,omitempty"`
	Indictment             nullable.Nullable[map[string]interface{}] `json:"indictment,omitempty"`
	IsLandmarkCase         *bool                                     `json:"is_landmark_case,omitempty"`
	LegalBasis             nullable.Nullable[[]string]               `json:"legal_basis,omitempty"`
	LegalFacts             nullable.Nullable[map[string]interface{}] `json:"legal_facts,omitempty"`
	NarcoticsDetails       nullable.Nullable[map[string]interface{}] `json:"narcotics_details,omitempty"`
	SummaryEn              nullable.Nullable[string]                 `json:"summary_en,omitempty"`
	SummaryId              nullable.Nullable[string]                 `json:"summary_id,omitempty"`
	Verdict                nullable.Nullable[map[string]interface{}] `json:"verdict,omitempty"`
}

// CaseStatisticsResponse Response for case statistics
type CaseStatisticsResponse struct {
	SentenceDistribution map[string]interface{} `json:"sentence_distribution"`
	TotalCases           int                    `json:"total_cases"`
	VerdictDistribution  map[string]interface{} `json:"verdict_distribution"`
}

// CitedPrecedent A precedent case cited in the opinion
type CitedPrecedent struct {
	// CaseId Unique identifier of the precedent case
	CaseId string `json:"case_id"`

	// CaseNumber Official case number
	CaseNumber string `json:"case_number"`

	// HowItApplies How this precedent applies to the current case
	HowItApplies string `json:"how_it_applies"`

	// Relevance Why this case is relevant
	Relevance string `json:"relevance"`

	// VerdictSummary Summary of the verdict
	VerdictSummary string `json:"verdict_summary"`
}

// ContinueDiscussionRequest defines model for ContinueDiscussionRequest.
type ContinueDiscussionRequest struct {
	// NumRounds Number of discussion rounds (each round = all judges respond)
	NumRounds *int `json:"num_rounds,omitempty"`
}

// ContinueDiscussionResponse defines model for ContinueDiscussionResponse.
type ContinueDiscussionResponse struct {
	NewMessages   []DeliberationMessage `json:"new_messages"`
	TotalMessages int                   `json:"total_messages"`
}

// CorruptionDetails Details specific to corruption cases
type CorruptionDetails struct {
	Position     nullable.Nullable[string] `json:"position,omitempty"`
	StateLossIdr float32                   `json:"state_loss_idr"`
}

// CouncilCaseType Types of legal cases
type CouncilCaseType string

// CouncilDefendantProfile Profile of the defendant in a case
type CouncilDefendantProfile struct {
	Age             nullable.Nullable[int]    `json:"age,omitempty"`
	IsFirstOffender *bool                     `json:"is_first_offender,omitempty"`
	Occupation      nullable.Nullable[string] `json:"occupation,omitempty"`
}

// CouncilSimilarCase A similar case found via semantic search
type CouncilSimilarCase struct {
	CaseId           string  `json:"case_id"`
	CaseNumber       string  `json:"case_number"`
	SentenceMonths   int     `json:"sentence_months"`
	SimilarityReason string  `json:"similarity_reason"`
	SimilarityScore  float32 `json:"similarity_score"`
	VerdictSummary   string  `json:"verdict_summary"`
}

// CreateSessionRequest defines model for CreateSessionRequest.
type CreateSessionRequest struct {
	// CaseSummary Summary of the case for deliberation
	CaseSummary string `json:"case_summary"`

	// CaseType Types of legal cases
	CaseType *CouncilCaseType `json:"case_type,omitempty"`

	// InputType Type of case input
	InputType *InputType `json:"input_type,omitempty"`

	// StructuredData Optional structured data that can be provided with case input
	StructuredData *StructuredCaseData `json:"structured_data,omitempty"`
}

// CreateSessionResponse Response after creating a session
type CreateSessionResponse struct {
	// InitialMessage A message in a deliberation session
	InitialMessage *DeliberationMessage `json:"initial_message,omitempty"`

	// ParsedCase Parsed and structured case information
	ParsedCase   ParsedCaseInput      `json:"parsed_case"`
	SessionId    string               `json:"session_id"`
	SimilarCases []CouncilSimilarCase `json:"similar_cases"`
}

// CreateSessionStreamEventData Data payload for streaming session creation events (SSE)
type CreateSessionStreamEventData struct {
	// AgentId Identifiers for the judicial AI agents
	AgentId *AgentId `json:"agent_id,omitempty"`

	// Content Event content, chunk text, or error text
	Content nullable.Nullable[string] `json:"content,omitempty"`

	// EventType Event types emitted while creating a deliberation session
	EventType CreateSessionStreamEventType `json:"event_type"`

	// FullContent Full message content on agent completion
	FullContent nullable.Nullable[string] `json:"full_content,omitempty"`

	// InitialMessage A message in a deliberation session
	InitialMessage *DeliberationMessage `json:"initial_message,omitempty"`

	// MessageId Message identifier for agent stream events
	MessageId nullable.Nullable[string] `json:"message_id,omitempty"`

	// ParsedCase Parsed and structured case information
	ParsedCase *ParsedCaseInput `json:"parsed_case,omitempty"`

	// SessionId Session identifier once the session has been created
	SessionId    nullable.Nullable[string]               `json:"session_id,omitempty"`
	SimilarCases nullable.Nullable[[]CouncilSimilarCase] `json:"similar_cases,omitempty"`

	// Status Progress status for setup events
	Status nullable.Nullable[string] `json:"status,omitempty"`

	// StatusCode HTTP-like status code for terminal error events
	StatusCode nullable.Nullable[int] `json:"status_code,omitempty"`
}

// CreateSessionStreamEventType Event types emitted while creating a deliberation session
type CreateSessionStreamEventType string

// DeliberationMessage A message in a deliberation session
type DeliberationMessage struct {
	CitedCases *[]string                 `json:"cited_cases,omitempty"`
	CitedLaws  *[]string                 `json:"cited_laws,omitempty"`
	Content    string                    `json:"content"`
	Id         string                    `json:"id"`
	Intent     nullable.Nullable[string] `json:"intent,omitempty"`

	// Sender Union type for message senders
	Sender    MessageSender                `json:"sender"`
	SessionId string                       `json:"session_id"`
	Timestamp nullable.Nullable[time.Time] `json:"timestamp,omitempty"`
}

// DeliberationPhase Current phase of a deliberation session
type DeliberationPhase string

// DeliberationSession A deliberation session
type DeliberationSession struct {
	// CaseInput Complete case input with raw and parsed data
	CaseInput   CaseInput                    `json:"case_input"`
	ConcludedAt nullable.Nullable[time.Time] `json:"concluded_at,omitempty"`
	CreatedAt   time.Time                    `json:"created_at"`

	// CurrentPhase Current phase of a deliberation session
	CurrentPhase *DeliberationPhase                        `json:"current_phase,omitempty"`
	Id           string                                    `json:"id"`
	LegalOpinion nullable.Nullable[map[string]interface{}] `json:"legal_opinion,omitempty"`
	Messages     *[]DeliberationMessage                    `json:"messages,omitempty"`

	// PhaseMetadata Metadata tracking the deliberation phase state
	PhaseMetadata *PhaseMetadata        `json:"phase_metadata,omitempty"`
	SimilarCases  *[]CouncilSimilarCase `json:"similar_cases,omitempty"`

	// Status Status of a deliberation session
	Status SessionStatus `json:"status"`

	// StructuredSummary Structured deliberation summary (populated in summary phase)
	StructuredSummary nullable.Nullable[map[string]interface{}] `json:"structured_summary,omitempty"`
	UpdatedAt         time.Time                                 `json:"updated_at"`
	UserId            nullable.Nullable[string]                 `json:"user_id,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error      string `json:"error"`
	StatusCode *int   `json:"status_code,omitempty"`
}

// GenerateOpinionRequest Request to generate a legal opinion
type GenerateOpinionRequest struct {
	IncludeDissent *bool `json:"include_dissent,omitempty"`
}

// GenerateOpinionResponse Response containing the generated legal opinion
type GenerateOpinionResponse struct {
	// Opinion Generated legal opinion from a deliberation session
	Opinion LegalOpinionDraft `json:"opinion"`
}

// GetCaseResponse Response for getting a single case
type GetCaseResponse struct {
	// Case A case record from the database
	Case CaseRecord `json:"case"`
}

// GetMessagesResponse Response for getting messages
type GetMessagesResponse struct {
	Messages []DeliberationMessage `json:"messages"`
}

// GetSessionResponse Response for getting a session
type GetSessionResponse struct {
	// Session A deliberation session
	Session DeliberationSession `json:"session"`
}

// InputType Type of case input
type InputType string

// LegalArguments Collected legal arguments from the deliberation
type LegalArguments struct {
	// ForConviction Arguments supporting conviction
	ForConviction *[]ArgumentPoint `json:"for_conviction,omitempty"`

	// ForLeniency Arguments supporting leniency
	ForLeniency *[]ArgumentPoint `json:"for_leniency,omitempty"`

	// ForSeverity Arguments supporting severity
	ForSeverity *[]ArgumentPoint `json:"for_severity,omitempty"`
}

// LegalOpinionDraft Generated legal opinion from a deliberation session
type LegalOpinionDraft struct {
	// ApplicableLaws Laws applicable to the case
	ApplicableLaws *[]ApplicableLaw `json:"applicable_laws,omitempty"`

	// CaseSummary Summary of the case
	CaseSummary string `json:"case_summary"`

	// CitedPrecedents Precedent cases cited in the opinion
	CitedPrecedents *[]CitedPrecedent `json:"cited_precedents,omitempty"`

	// DissentingViews Dissenting opinions from judges
	DissentingViews *[]string `json:"dissenting_views,omitempty"`

	// GeneratedAt When the opinion was generated
	GeneratedAt time.Time `json:"generated_at"`

	// LegalArguments Collected legal arguments from the deliberation
	LegalArguments LegalArguments `json:"legal_arguments"`

	// SentenceRecommendation Recommendation for sentencing
	SentenceRecommendation SentenceRecommendation `json:"sentence_recommendation"`

	// SessionId Session this opinion belongs to
	SessionId string `json:"session_id"`

	// VerdictRecommendation Recommendation for the verdict
	VerdictRecommendation VerdictRecommendation `json:"verdict_recommendation"`
}

// ListSessionsResponse Response for listing sessions
type ListSessionsResponse struct {
	Pagination map[string]int        `json:"pagination"`
	Sessions   []DeliberationSession `json:"sessions"`
}

// MessageSender Union type for message senders
type MessageSender struct {
	union json.RawMessage
}

// NarcoticsDetails Details specific to narcotics cases
type NarcoticsDetails struct {
	// Intent Intent classification for narcotics cases
	Intent      *NarcoticsIntent `json:"intent,omitempty"`
	Substance   string           `json:"substance"`
	WeightGrams float32          `json:"weight_grams"`
}

// NarcoticsIntent Intent classification for narcotics cases
type NarcoticsIntent string

// ParsedCaseInput Parsed and structured case information
type ParsedCaseInput struct {
	// CaseType Types of legal cases
	CaseType CouncilCaseType `json:"case_type"`
	Charges  *[]string       `json:"charges,omitempty"`

	// Corruption Details specific to corruption cases
	Corruption *CorruptionDetails `json:"corruption,omitempty"`

	// DefendantProfile Profile of the defendant in a case
	DefendantProfile *CouncilDefendantProfile `json:"defendant_profile,omitempty"`
	KeyFacts         *[]string                `json:"key_facts,omitempty"`

	// Narcotics Details specific to narcotics cases
	Narcotics *NarcoticsDetails `json:"narcotics,omitempty"`
	Summary   string            `json:"summary"`
}

// PhaseMetadata Metadata tracking the deliberation phase state
type PhaseMetadata struct {
	// AgreementMap Tracks agent positions and agreement across deliberation issues
	AgreementMap *AgreementMap `json:"agreement_map,omitempty"`
	PhaseHistory *[]struct {
		EnteredAt *time.Time `json:"entered_at,omitempty"`
		Phase     *string    `json:"phase,omitempty"`
		Round     *int       `json:"round,omitempty"`
	} `json:"phase_history,omitempty"`
}

// PositionStance An agent's stance on a deliberation issue
type PositionStance string

// SearchCasesRequest Request for searching cases
type SearchCasesRequest struct {
	// Filters Optional structured data that can be provided with case input
	Filters        *StructuredCaseData `json:"filters,omitempty"`
	Limit          *int                `json:"limit,omitempty"`
	Query          string              `json:"query"`
	SemanticSearch *bool               `json:"semantic_search,omitempty"`
}

// SearchCasesResponse Response for case search
type SearchCasesResponse struct {
	Cases []CaseRecord `json:"cases"`
	Total int          `json:"total"`
}

// SendMessageRequest defines model for SendMessageRequest.
type SendMessageRequest struct {
	// Content Message content to send to the council
	Content string `json:"content"`

	// TargetAgent Target a specific agent or all agents
	TargetAgent nullable.Nullable[SendMessageRequestTargetAgent] `json:"target_agent,omitempty"`
}

// SendMessageRequestTargetAgent Target a specific agent or all agents
type SendMessageRequestTargetAgent string

// SendMessageResponse defines model for SendMessageResponse.
type SendMessageResponse struct {
	AgentResponses []DeliberationMessage `json:"agent_responses"`

	// UserMessage A message in a deliberation session
	UserMessage DeliberationMessage `json:"user_message"`
}

// SentenceRange A range for sentencing recommendations
type SentenceRange struct {
	// Maximum Maximum sentence value
	Maximum int `json:"maximum"`

	// Minimum Minimum sentence value
	Minimum int `json:"minimum"`

	// Recommended Recommended sentence value
	Recommended int `json:"recommended"`
}

// SentenceRecommendation Recommendation for sentencing
type SentenceRecommendation struct {
	// AdditionalPenalties Additional penalties recommended
	AdditionalPenalties *[]string `json:"additional_penalties,omitempty"`

	// FineIdr A range for sentencing recommendations
	FineIdr SentenceRange `json:"fine_idr"`

	// ImprisonmentMonths A range for sentencing recommendations
	ImprisonmentMonths SentenceRange `json:"imprisonment_months"`
}

// SessionStatus Status of a deliberation session
type SessionStatus string

// StreamContinueRequest defines model for StreamContinueRequest.
type StreamContinueRequest struct {
	// NumRounds Number of discussion rounds (each round = all judges respond)
	NumRounds *int `json:"num_rounds,omitempty"`
}

// StreamEventData Data payload for streaming events (SSE)
type StreamEventData struct {
	// AgentId Identifiers for the judicial AI agents
	AgentId *AgentId `json:"agent_id,omitempty"`

	// Content Event content (chunk text or message)
	Content *string `json:"content,omitempty"`

	// EventType Types of streaming events
	EventType *StreamEventType `json:"event_type,omitempty"`

	// FullContent Full message content (only on agent_complete)
	FullContent nullable.Nullable[string] `json:"full_content,omitempty"`

	// MessageId Message identifier
	MessageId nullable.Nullable[string] `json:"message_id,omitempty"`
}

// StreamEventType Types of streaming events
type StreamEventType string

// StreamMessageRequest defines model for StreamMessageRequest.
type StreamMessageRequest struct {
	// Content Message content to send
	Content string `json:"content"`

	// TargetAgent Target a specific agent or all agents
	TargetAgent nullable.Nullable[StreamMessageRequestTargetAgent] `json:"target_agent,omitempty"`
}

// StreamMessageRequestTargetAgent Target a specific agent or all agents
type StreamMessageRequestTargetAgent string

// StructuredCaseData Optional structured data that can be provided with case input
type StructuredCaseData struct {
	// CaseType Types of legal cases
	CaseType               *CouncilCaseType           `json:"case_type,omitempty"`
	DefendantAge           nullable.Nullable[int]     `json:"defendant_age,omitempty"`
	DefendantFirstOffender nullable.Nullable[bool]    `json:"defendant_first_offender,omitempty"`
	StateLossIdr           nullable.Nullable[float32] `json:"state_loss_idr,omitempty"`
	SubstanceType          nullable.Nullable[string]  `json:"substance_type,omitempty"`
	WeightGrams            nullable.Nullable[float32] `json:"weight_grams,omitempty"`
}

// SystemSender defines model for SystemSender.
type SystemSender struct {
	Type SystemSenderType `json:"type"`
}

// SystemSenderType defines model for SystemSender.Type.
type SystemSenderType string

// UserSender defines model for UserSender.
type UserSender struct {
	Type UserSenderType `json:"type"`
}

// UserSenderType defines model for UserSender.Type.
type UserSenderType string

// VerdictDecision Possible verdict decisions
type VerdictDecision string

// VerdictRecommendation Recommendation for the verdict
type VerdictRecommendation struct {
	// Confidence Confidence level (high, medium, low)
	Confidence string `json:"confidence"`

	// Decision Possible verdict decisions
	Decision VerdictDecision `json:"decision"`

	// Reasoning Reasoning behind the recommendation
	Reasoning string `json:"reasoning"`
}

// GetCouncilCasesByTypeParams defines parameters for GetCouncilCasesByType.
type GetCouncilCasesByTypeParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// SearchCouncilCasesGetParams defines parameters for SearchCouncilCasesGet.
type SearchCouncilCasesGetParams struct {
	Query    string           `form:"query" json:"query"`
	Limit    *int             `form:"limit,omitempty" json:"limit,omitempty"`
	Semantic *bool            `form:"semantic,omitempty" json:"semantic,omitempty"`
	CaseType *CouncilCaseType `form:"case_type,omitempty" json:"case_type,omitempty"`
}

// GetCouncilMessagesParams defines parameters for GetCouncilMessages.
type GetCouncilMessagesParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListCouncilSessionsParams defines parameters for ListCouncilSessions.
type ListCouncilSessionsParams struct {
	// Status Filter by session status
	Status *ListCouncilSessionsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit  *int                             `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int                             `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListCouncilSessionsParamsStatus defines parameters for ListCouncilSessions.
type ListCouncilSessionsParamsStatus string

// SearchCouncilCasesJSONRequestBody defines body for SearchCouncilCases for application/json ContentType.
type SearchCouncilCasesJSONRequestBody = SearchCasesRequest

// ContinueCouncilDiscussionJSONRequestBody defines body for ContinueCouncilDiscussion for application/json ContentType.
type ContinueCouncilDiscussionJSONRequestBody = ContinueDiscussionRequest

// SendCouncilMessageJSONRequestBody defines body for SendCouncilMessage for application/json ContentType.
type SendCouncilMessageJSONRequestBody = SendMessageRequest

// GenerateCouncilOpinionJSONRequestBody defines body for GenerateCouncilOpinion for application/json ContentType.
type GenerateCouncilOpinionJSONRequestBody = GenerateOpinionRequest

// StreamCouncilContinueJSONRequestBody defines body for StreamCouncilContinue for application/json ContentType.
type StreamCouncilContinueJSONRequestBody = StreamContinueRequest

// StreamCouncilMessageJSONRequestBody defines body for StreamCouncilMessage for application/json ContentType.
type StreamCouncilMessageJSONRequestBody = StreamMessageRequest

// CreateCouncilSessionJSONRequestBody defines body for CreateCouncilSession for application/json ContentType.
type CreateCouncilSessionJSONRequestBody = CreateSessionRequest

// AsUserSender returns the union data inside the MessageSender as a UserSender
func (t MessageSender) AsUserSender() (UserSender, error) {
	var body UserSender
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUserSender overwrites any union data inside the MessageSender as the provided UserSender
func (t *MessageSender) FromUserSender(v UserSender) error {
	v.Type = "user"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUserSender performs a merge with any union data inside the MessageSender, using the provided UserSender
func (t *MessageSender) MergeUserSender(v UserSender) error {
	v.Type = "user"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAgentSender returns the union data inside the MessageSender as a AgentSender
func (t MessageSender) AsAgentSender() (AgentSender, error) {
	var body AgentSender
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAgentSender overwrites any union data inside the MessageSender as the provided AgentSender
func (t *MessageSender) FromAgentSender(v AgentSender) error {
	v.Type = "agent"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAgentSender performs a merge with any union data inside the MessageSender, using the provided AgentSender
func (t *MessageSender) MergeAgentSender(v AgentSender) error {
	v.Type = "agent"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSystemSender returns the union data inside the MessageSender as a SystemSender
func (t MessageSender) AsSystemSender() (SystemSender, error) {
	var body SystemSender
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSystemSender overwrites any union data inside the MessageSender as the provided SystemSender
func (t *MessageSender) FromSystemSender(v SystemSender) error {
	v.Type = "system"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSystemSender performs a merge with any union data inside the MessageSender, using the provided SystemSender
func (t *MessageSender) MergeSystemSender(v SystemSender) error {
	v.Type = "system"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t MessageSender) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t MessageSender) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "agent":
		return t.AsAgentSender()
	case "system":
		return t.AsSystemSender()
	case "user":
		return t.AsUserSender()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t MessageSender) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *MessageSender) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness probe
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Readiness probe
	// (GET /ready)
	GetReady(w http.ResponseWriter, r *http.Request)
	// Get cases by type
	// (GET /v1/council/cases/by-type/{case_type})
	GetCouncilCasesByType(w http.ResponseWriter, r *http.Request, caseType CouncilCaseType, params GetCouncilCasesByTypeParams)
	// Search similar cases
	// (GET /v1/council/cases/search)
	SearchCouncilCasesGet(w http.ResponseWriter, r *http.Request, params SearchCouncilCasesGetParams)
	// Search similar cases
	// (POST /v1/council/cases/search)
	SearchCouncilCases(w http.ResponseWriter, r *http.Request)
	// Get case statistics
	// (GET /v1/council/cases/statistics)
	GetCouncilCaseStatistics(w http.ResponseWriter, r *http.Request)
	// Get case details
	// (GET /v1/council/cases/{case_id})
	GetCouncilCase(w http.ResponseWriter, r *http.Request, caseId string)
	// Continue deliberation
	// (POST /v1/council/deliberation/{session_id}/continue)
	ContinueCouncilDiscussion(w http.ResponseWriter, r *http.Request, sessionId string)
	// Download deliberation as PDF
	// (GET /v1/council/deliberation/{session_id}/download/pdf)
	DownloadCouncilPDF(w http.ResponseWriter, r *http.Request, sessionId string)
	// Send message to council
	// (POST /v1/council/deliberation/{session_id}/message)
	SendCouncilMessage(w http.ResponseWriter, r *http.Request, sessionId string)
	// Get deliberation messages
	// (GET /v1/council/deliberation/{session_id}/messages)
	GetCouncilMessages(w http.ResponseWriter, r *http.Request, sessionId string, params GetCouncilMessagesParams)
	// Get generated opinion
	// (GET /v1/council/deliberation/{session_id}/opinion)
	GetCouncilOpinion(w http.ResponseWriter, r *http.Request, sessionId string)
	// Generate legal opinion
	// (POST /v1/council/deliberation/{session_id}/opinion)
	GenerateCouncilOpinion(w http.ResponseWriter, r *http.Request, sessionId string)
	// Stream continued deliberation
	// (POST /v1/council/deliberation/{session_id}/stream/continue)
	StreamCouncilContinue(w http.ResponseWriter, r *http.Request, sessionId string)
	// Stream remaining initial opinions from judges
	// (POST /v1/council/deliberation/{session_id}/stream/initial)
	StreamCouncilInitial(w http.ResponseWriter, r *http.Request, sessionId string)
	// Stream message response
	// (POST /v1/council/deliberation/{session_id}/stream/message)
	StreamCouncilMessage(w http.ResponseWriter, r *http.Request, sessionId string)
	// List deliberation sessions
	// (GET /v1/council/sessions)
	ListCouncilSessions(w http.ResponseWriter, r *http.Request, params ListCouncilSessionsParams)
	// Create new deliberation session
	// (POST /v1/council/sessions)
	CreateCouncilSession(w http.ResponseWriter, r *http.Request)
	// Delete session
	// (DELETE /v1/council/sessions/{session_id})
	DeleteCouncilSession(w http.ResponseWriter, r *http.Request, sessionId string)
	// Get session details
	// (GET /v1/council/sessions/{session_id})
	GetCouncilSession(w http.ResponseWriter, r *http.Request, sessionId string)
	// Conclude deliberation session
	// (POST /v1/council/sessions/{session_id}/conclude)
	ConcludeCouncilSession(w http.ResponseWriter, r *http.Request, sessionId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Liveness probe
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Readiness probe
// (GET /ready)
func (_ Unimplemented) GetReady(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get cases by type
// (GET /v1/council/cases/by-type/{case_type})
func (_ Unimplemented) GetCouncilCasesByType(w http.ResponseWriter, r *http.Request, caseType CouncilCaseType, params GetCouncilCasesByTypeParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Search similar cases
// (GET /v1/council/cases/search)
func (_ Unimplemented) SearchCouncilCasesGet(w http.ResponseWriter, r *http.Request, params SearchCouncilCasesGetParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Search similar cases
// (POST /v1/council/cases/search)
func (_ Unimplemented) SearchCouncilCases(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get case statistics
// (GET /v1/council/cases/statistics)
func (_ Unimplemented) GetCouncilCaseStatistics(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get case details
// (GET /v1/council/cases/{case_id})
func (_ Unimplemented) GetCouncilCase(w http.ResponseWriter, r *http.Request, caseId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Continue deliberation
// (POST /v1/council/deliberation/{session_id}/continue)
func (_ Unimplemented) ContinueCouncilDiscussion(w http.ResponseWriter, r *http.Request, sessionId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Download deliberation as PDF
// (GET /v1/council/deliberation/{session_id}/download/pdf)
func (_ Unimplemented) DownloadCouncilPDF(w http.ResponseWriter, r *http.Request, sessionId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Send message to council
// (POST /v1/council/deliberation/{session_id}/message)
func (_ Unimplemented) SendCouncilMessage(w http.ResponseWriter, r *http.Request, sessionId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get deliberation messages
// (GET /v1/council/deliberation/{session_id}/messages)
func (_ Unimplemented) GetCouncilMessages(w http.ResponseWriter, r *http.Request, sessionId string, params GetCouncilMessagesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get generated opinion
// (GET /v1/council/deliberation/{session_id}/opinion)
func (_ Unimplemented) GetCouncilOpinion(w http.ResponseWriter, r *http.Request, sessionId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Generate legal opinion
// (POST /v1/council/deliberation/{session_id}/opinion)
func (_ Unimplemented) GenerateCouncilOpinion(w http.ResponseWriter, r *http.Request, sessionId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stream continued deliberation
// (POST /v1/council/deliberation/{session_id}/stream/continue)
func (_ Unimplemented) StreamCouncilContinue(w http.ResponseWriter, r *http.Request, sessionId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stream remaining initial opinions from judges
// (POST /v1/council/deliberation/{session_id}/stream/initial)
func (_ Unimplemented) StreamCouncilInitial(w http.ResponseWriter, r *http.Request, sessionId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stream message response
// (POST /v1/council/deliberation/{session_id}/stream/message)
func (_ Unimplemented) StreamCouncilMessage(w http.ResponseWriter, r *http.Request, sessionId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List deliberation sessions
// (GET /v1/council/sessions)
func (_ Unimplemented) ListCouncilSessions(w http.ResponseWriter, r *http.Request, params ListCouncilSessionsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create new deliberation session
// (POST /v1/council/sessions)
func (_ Unimplemented) CreateCouncilSession(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete session
// (DELETE /v1/council/sessions/{session_id})
func (_ Unimplemented) DeleteCouncilSession(w http.ResponseWriter, r *http.Request, sessionId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get session details
// (GET /v1/council/sessions/{session_id})
func (_ Unimplemented) GetCouncilSession(w http.ResponseWriter, r *http.Request, sessionId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Conclude deliberation session
// (POST /v1/council/sessions/{session_id}/conclude)
func (_ Unimplemented) ConcludeCouncilSession(w http.ResponseWriter, r *http.Request, sessionId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReady operation middleware
func (siw *ServerInterfaceWrapper) GetReady(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReady(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCouncilCasesByType operation middleware
func (siw *ServerInterfaceWrapper) GetCouncilCasesByType(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "case_type" -------------
	var caseType CouncilCaseType

	err = runtime.BindStyledParameterWithOptions("simple", "case_type", chi.URLParam(r, "case_type"), &caseType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "case_type", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCouncilCasesByTypeParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCouncilCasesByType(w, r, caseType, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchCouncilCasesGet operation middleware
func (siw *ServerInterfaceWrapper) SearchCouncilCasesGet(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchCouncilCasesGetParams

	// ------------- Required query parameter "query" -------------

	if paramValue := r.URL.Query().Get("query"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "query"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "query", r.URL.Query(), &params.Query, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "query", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "semantic" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "semantic", r.URL.Query(), &params.Semantic, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "semantic", Err: err})
		return
	}

	// ------------- Optional query parameter "case_type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "case_type", r.URL.Query(), &params.CaseType, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "case_type", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchCouncilCasesGet(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchCouncilCases operation middleware
func (siw *ServerInterfaceWrapper) SearchCouncilCases(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchCouncilCases(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCouncilCaseStatistics operation middleware
func (siw *ServerInterfaceWrapper) GetCouncilCaseStatistics(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCouncilCaseStatistics(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCouncilCase operation middleware
func (siw *ServerInterfaceWrapper) GetCouncilCase(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "case_id" -------------
	var caseId string

	err = runtime.BindStyledParameterWithOptions("simple", "case_id", chi.URLParam(r, "case_id"), &caseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "case_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCouncilCase(w, r, caseId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ContinueCouncilDiscussion operation middleware
func (siw *ServerInterfaceWrapper) ContinueCouncilDiscussion(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "session_id" -------------
	var sessionId string

	err = runtime.BindStyledParameterWithOptions("simple", "session_id", chi.URLParam(r, "session_id"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "session_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ContinueCouncilDiscussion(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DownloadCouncilPDF operation middleware
func (siw *ServerInterfaceWrapper) DownloadCouncilPDF(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "session_id" -------------
	var sessionId string

	err = runtime.BindStyledParameterWithOptions("simple", "session_id", chi.URLParam(r, "session_id"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "session_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadCouncilPDF(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendCouncilMessage operation middleware
func (siw *ServerInterfaceWrapper) SendCouncilMessage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "session_id" -------------
	var sessionId string

	err = runtime.BindStyledParameterWithOptions("simple", "session_id", chi.URLParam(r, "session_id"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "session_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendCouncilMessage(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCouncilMessages operation middleware
func (siw *ServerInterfaceWrapper) GetCouncilMessages(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "session_id" -------------
	var sessionId string

	err = runtime.BindStyledParameterWithOptions("simple", "session_id", chi.URLParam(r, "session_id"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "session_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCouncilMessagesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCouncilMessages(w, r, sessionId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCouncilOpinion operation middleware
func (siw *ServerInterfaceWrapper) GetCouncilOpinion(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "session_id" -------------
	var sessionId string

	err = runtime.BindStyledParameterWithOptions("simple", "session_id", chi.URLParam(r, "session_id"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "session_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCouncilOpinion(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateCouncilOpinion operation middleware
func (siw *ServerInterfaceWrapper) GenerateCouncilOpinion(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "session_id" -------------
	var sessionId string

	err = runtime.BindStyledParameterWithOptions("simple", "session_id", chi.URLParam(r, "session_id"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "session_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateCouncilOpinion(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamCouncilContinue operation middleware
func (siw *ServerInterfaceWrapper) StreamCouncilContinue(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "session_id" -------------
	var sessionId string

	err = runtime.BindStyledParameterWithOptions("simple", "session_id", chi.URLParam(r, "session_id"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "session_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamCouncilContinue(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamCouncilInitial operation middleware
func (siw *ServerInterfaceWrapper) StreamCouncilInitial(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "session_id" -------------
	var sessionId string

	err = runtime.BindStyledParameterWithOptions("simple", "session_id", chi.URLParam(r, "session_id"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "session_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamCouncilInitial(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamCouncilMessage operation middleware
func (siw *ServerInterfaceWrapper) StreamCouncilMessage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "session_id" -------------
	var sessionId string

	err = runtime.BindStyledParameterWithOptions("simple", "session_id", chi.URLParam(r, "session_id"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "session_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamCouncilMessage(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCouncilSessions operation middleware
func (siw *ServerInterfaceWrapper) ListCouncilSessions(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCouncilSessionsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCouncilSessions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCouncilSession operation middleware
func (siw *ServerInterfaceWrapper) CreateCouncilSession(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, TurnstileTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCouncilSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCouncilSession operation middleware
func (siw *ServerInterfaceWrapper) DeleteCouncilSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "session_id" -------------
	var sessionId string

	err = runtime.BindStyledParameterWithOptions("simple", "session_id", chi.URLParam(r, "session_id"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "session_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCouncilSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCouncilSession operation middleware
func (siw *ServerInterfaceWrapper) GetCouncilSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "session_id" -------------
	var sessionId string

	err = runtime.BindStyledParameterWithOptions("simple", "session_id", chi.URLParam(r, "session_id"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "session_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCouncilSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ConcludeCouncilSession operation middleware
func (siw *ServerInterfaceWrapper) ConcludeCouncilSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "session_id" -------------
	var sessionId string

	err = runtime.BindStyledParameterWithOptions("simple", "session_id", chi.URLParam(r, "session_id"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "session_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConcludeCouncilSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ready", wrapper.GetReady)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/council/cases/by-type/{case_type}", wrapper.GetCouncilCasesByType)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/council/cases/search", wrapper.SearchCouncilCasesGet)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/council/cases/search", wrapper.SearchCouncilCases)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/council/cases/statistics", wrapper.GetCouncilCaseStatistics)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/council/cases/{case_id}", wrapper.GetCouncilCase)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/council/deliberation/{session_id}/continue", wrapper.ContinueCouncilDiscussion)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/council/deliberation/{session_id}/download/pdf", wrapper.DownloadCouncilPDF)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/council/deliberation/{session_id}/message", wrapper.SendCouncilMessage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/council/deliberation/{session_id}/messages", wrapper.GetCouncilMessages)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/council/deliberation/{session_id}/opinion", wrapper.GetCouncilOpinion)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/council/deliberation/{session_id}/opinion", wrapper.GenerateCouncilOpinion)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/council/deliberation/{session_id}/stream/continue", wrapper.StreamCouncilContinue)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/council/deliberation/{session_id}/stream/initial", wrapper.StreamCouncilInitial)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/council/deliberation/{session_id}/stream/message", wrapper.StreamCouncilMessage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/council/sessions", wrapper.ListCouncilSessions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/council/sessions", wrapper.CreateCouncilSession)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/council/sessions/{session_id}", wrapper.DeleteCouncilSession)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/council/sessions/{session_id}", wrapper.GetCouncilSession)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/council/sessions/{session_id}/conclude", wrapper.ConcludeCouncilSession)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x963LbuJrgq6C4UzVJlSxLvqTTnjo15cS5x4k3dp9zduKs+hMJSTBJkA2AVrQpbe1D",
	"7BPuk2zhRoIkKFG2M53u6fPndCwQ+PAB3/2Cb0GYpXlGMRU8OPkW8HCBU1D/eTrHVLyJ5H9GmIeM5IJk",
	"NDgJ3kSYCjIjmHE0yxgSC4xuioiEBBJ0+gbBXM02CDAt0uDkc8AFI6EIBsGiSIESrv6TcJExAjT4MgjE",
	"KsfBiRpH58F6oNe+yDjRSzYhOKV6kX/lKDeDUEYRIJ7jkMxIiAjnBUaEKuAinJApZqC+HgQ5y3LMBMFq",
	"m2pke4mrxndmxikmdI4iwsOCcxwFHtgZBp5RQucTXqQpsFV78vHeAeKYCkxDjMwolM0UsHZj5TTeNbKC",
	"RhMuQODID7sagWiRTjFDywWWmCAOupbAkfm+nJ9QgeeYyQW4ABoqtPwLw7PgJPhv+9VF2Te3ZN+e0KUe",
	"vVa7/60gTEL12aC2nMyHmsZWqruQTW9wKMq7cIlphJmEp356ClsTEm2D1F7mtV3gW3k71RSeW9jYjPp1",
	"UC3oB5VhnGIqziH3HAuDMOb6gMuD4AhohMB+iCBkGeeeq8dbNzfM6C1mc3mJJjzMmLnFMygSEZyMBo3l",
	"L1iWZ0zTyszMiZZELFAKNxkjYuWA8Wg0HO2Nh6PHwSCYZSwFEZwEsyQDUV0Xfbnkvg2A8jyiSG0Lkov6",
	"OXX8feuZlUxg7cF3udlv6+ZuzyEvtzmJ8QqJrIX5R/Yw0d51MRodYlRb8nHgWTIBLiYu5sMFDuPNmP/k",
	"0qIhczkPcuZBeh4fLTI8Z5hzktFJmBVUNBfzfKFoqtdgH1pP8zwhIUwT/B6Wfu5bjkAJLBHDM8ywpvH6",
	"Ha192ZzorPpXhZalj98tsuWEiIla1jNx8Dpbav4moTGj5InLKUPg2DdnAstJBXhryk/2JzuPnPoRHs6H",
	"A3TKBAkTjA7QL7+gw/H++Oeff34cbOMg9QXrl6S1RS97YfMiVReU2IOtnQvihM4TjMCMQ7kcaKVggueQ",
	"oCwn1CcG7TftaS/1pNMiSbDY01Pquew3Q/Txwwt5mUPCsSPYBAhC59c0o8lKgcCLqZQFgtxacPR0/+//",
	"/F9EMyS5j/yCD9AioxmTkpxf00fXwf8AOkfnRULgOng8kGIeYswQx8lsr0QpR4+ug0tYAZpilmMaQQ5C",
	"jc/YNSVUsCwqQpGxFZoxSAmdD9FlQYS6xlKRiQjDoUBMyRop54EjQAnh4poSgdMhOoevJC1S9L+PRmiZ",
	"sYgPryUq8VdI80Qe1hVmEcRLQAKzaRELglLMijmJgaIYF0DnQBHFc2CAOJ5iDgx9ytExSklCgA1QKvlv",
	"sSCooLxg6AI4JPqeXZGcxBkbBoMgha/vMZ2LRXByNBp57jbPChbiiRZt/UUjF8xM27pb9krZIegRFyyj",
	"8wFKs0gKKjxASwzxYx+p8SJXoofOJ5IaPQT8XP4ZVeM0NZeXchBI/KvvWpObPwBjsGrRnDNDDSfOXn2U",
	"JsF5Q/PCQw7PM3nUQvMVROQgLUWZZD00QjkwjiMUgYC2simHT6wGsulU1OpXcuB6EOgpFe62qmRqaAW/",
	"xAcsJ8RuZjOLcuBzv6tD0IWwTzjMWOTjSwpVTP2MZixLtVYOAqaaNzf0GuB4YpSLk28BLZJEkmhwIliB",
	"PbdLje+D0+dZQUOSSFgtZsOMsUIBOomwAJLwDUtW2w2zgokJhRT3g1ANtyBuHR7hkChxH4Ho+8VM8jsq",
	"5PXe8IWjI1SfzAjjYpLNZqWO3fH1NMsSDLT+dW8k4K+CQahQzTDXatt2TGvVvjUZoREJhRVY22fhkwRo",
	"lAKLSyoqtaIZJNy7SSWiJlPgRBNvJwvqWN+wJDvRDELR73pRYGEmSMh3upTGpppg2us87HCN4a3DbzGT",
	"KO8BybqDP1xKfYDLbX3CPM8o92pd+hcljxXb4OVXLUZhNY1JRCSc08Kqma3lRSYgqWRPmxrM7rbN1LQJ",
	"nWkHHeB0zO1lokTg6ILhEEfYr+Dl9keNm1B+YPW7Ls1OsUfi4cu/UPJbgREp3TlWCa+vEnSx3IpF1+f9",
	"OJtpX5CC0Yy6j1JfwdNU7QvGNoHJcIJvwave/2Ox0pNrMc6RGSuC7rvf7dC5rPtwLK1sswjs0dQR6sLd",
	"XruXpfA8o4LQAp9pRxXJ6Cf8W4G5aHtQaJFOlL3Ia0xx3DRiP5Tma1ROqr1MHD3CEC6My+lvCJIE3RTR",
	"HEukSnKOHmudVarOwcnhIEgJ1f897meQ+rZTcZDGfvBykmLOYY7rXHuTZnDmuFvO9cdt1dKyEXd2D/Tu",
	"AdeAaX3vPzmrkJxVrL9pNqsfKmenyFClxyDLjupoyR1n6nbRIEDgSZJxPiGRovBtPqDGvhsT+DdaV8ba",
	"7rJVjrm8b9pStNuybrtSRgauFhcMgjmmmEm2zEhKKCTBIMjEAjOvo9lAcWbVmQuWzUjigcb8YCm81H8k",
	"9wXLgFq+yX6qGOEeHaykxC4VLAvDIoeeZ7ruPoFLkpIE2HPwyeNTxPXPmk/OFInfEmm8ptKQDxHHwMLF",
	"JqmzTXq0r58VpGlGxaJDYhu4iFhNtFvZP1U1qnSRbvdnevj93Rh5a3kf3D4e30SBl4IYBoEv8Wb+rgDq",
	"K7jMIbNmyMRxOIxHo9FIsXD7l+PRAxtld7SSuWBFKAqGo4kyvrd8e1kOl2ufyS+8x2px1+MItmq1MBOY",
	"oVB+pfxLiOtPPY4CIkglK+4ov+7nNzCwdVGxuciVVt1L0nqYzjYfjgNHfUtNGLae0KVgGNIXt5iKM3ND",
	"GqIVBKAcVkkGkaIDrr6QZ2WgMIeXUYTlNBw9urx88djH+3eNS4WZJHmP2q/gRebnAQoXBY2RwF/FAGUM",
	"YcYypv4ZDHoY4XKufnTZgThLbbMiSSadML8skgSZy2tBVyHaud6L8qHpi78V5oehBfO11xIyw1xTSB6+",
	"BlZfAXPcfeB9SKprcGtzB12TTUUoFri8nwvgaIqxuagqvLtd33tAUt7mC5GqYcG9CpYKcyE9QFMfFkW+",
	"A+b1p5MwizxM+PXV1cVeQmJsV5DDdAIDZkpTNLS0bb0uZd+hrV04kV/71UQvlA6MUyKkob9cSA3UkR61",
	"KHElSqq8C4Xq6k5VV0LzJy6ASbahWEr5V0Od2P2w+pPCkVeX9hGeR6G0XEEpzh07aKgwRBh6qtuon7/0",
	"jwsMzCwJLO81ScXw2nyqy1UpNrspa4qv0f430Z3BrUmJ2C6oBUkxF5DmNeU3AoH35E/bCasZJIiCQV0o",
	"G7gr9Pjuv3s9LhZea+O58efk8mepk2694tI2DKXCnOXYJMtEeArqpjrR9aB0d269uYZAfTe332VVpoAN",
	"t2zkny7bDzMaJkWEowmIu57TIDAEvmmO9jca6ZN80UNgtQ+x++Jrr7d1S/bxYLueFT+BPoATR+1zkmIB",
	"fawEtclzO9gnK3cHtI8O7ArKjVaMlSdqcN0K6rb6yjGNO22swUd5lhcJGOey/atC3OPua1idY5FHO1/D",
	"gmPWLxbhZUdW1DnkVyOHGlA+9vRCybWW+Yztn7cpG9uUg4bYrBZ+pfxVAn/UhOIY8k0jUv2ARIbm5hME",
	"W7I6iGYqk4hwjhvJQH6/0roPhFvtXCkHgFAdyMclvNEWcB1esenOv5eTGGDOGMzagRk7kR/fQkere8Wg",
	"5lhYU13nwYRdIes+7N6EyH1+hi5YDSfjO8LreJ3roH4f33hjQxtd3K+w6O8xaZxBh9DlldDuuxUr5zu8",
	"DV7IK3eT11stNZYqK8TRUqR17jj3nEh4LZG04i3qhtucG1+6TJYkOKwIyqa5cCe9YlPS8yxjKomRhB0J",
	"1uV8TkqO80FPQVdPWPPIOAlHginBNFz1hKIc/pAwcHyLGRF9YSiHPwwMPp7b5nEt0F75uaq+Aj1NqyqR",
	"07GM3EXew5K76Z71pMp+u6+lk/qMql1d1F41Vpl3ZajY62Fww9q8K3reT4Wrh+o9mzIil9D55JZgH2rP",
	"yhF2dUO+Onga7GKXlhLW6FzNYDeu7VJl/5efuCneG1U0rdCDy5a2iumKibmBHYbDLE0xjcr41WYdV3/2",
	"qf5VT2eZivLbjU9xktE5RyLbFOffDby/66+a0G3yYteOq0EAnWB04699ND7p9Z5wK3j7ahMJ4cJxfnvC",
	"yjAntMRSV5Z/O3rXTl6yK9xFLSlleb9IgtpGBbgPV3Ufiy91Rt4sKfMlmqxLS/tB5PQR4Sb+LLT5kEKe",
	"y1tmYwMbAwKX1p/CV1zgtJMu1K/lYGlBdQ39hWNWOYzMGa4+qNw9vfv1IMgo/jgLTj5vRnxtqh7RjZ5j",
	"a5tZf1kPgg82wr9TJkSZF9CRCFG54zZBU679Rg9X+XLTqiqqxTqWmMwXYjJnkPK7JEyUkzem8l3OJnDt",
	"Cj0dbwkT4FziResA8qa2sWN11BwzLil3Uij52shhK2hMs6W/WK8ZxGgLXp0RDTRClXfCasoaUZ2etLvm",
	"9S6Aze/nLq5ySrYu30zZqSXI5lVKSY9NtDJR1oMgxqsqefSO26nSZfrefGczu+VBmPTxTXHzulfNE4/T",
	"vyBpJ8XWi1BTaLWLWOUZeYKvpoxtkuo6vM08yqnZK92Dujx11Y3whpeICsx2dHiV/lZ/dWeHT6md2rrV",
	"lGhUaW6qptU8SNfStksQHW6hUKzZhP3PHJggKt2KZpMy3czHMC5VypAq+djq7dJhQDlemaBelj4jiZBi",
	"9w4JH4MgISmpO8bG3pq63wrspQCpuuhUqIlJherlZHOpRk/to5MapnbIme7OydohvOv4qzpSIXv4Pe2J",
	"6fH+PdLIqFvdSUxdeQbnjRQDkSklrDRTNVOtZzAdNxOYxp47KqT8EFUFVcPbo351C851rkDGVPZrqwJe",
	"qeeEVyXwSpm/AQZLoLoYaUOF/CCAROFuN8f4pmBcDeldqbQ6HMzM7w+eTas8/vdJ6mjstzbfoAV9Bxq0",
	"ZQnUH6xm8gfDhNRQyYXq1pfHxWpTnVu31ZQPliWSt5AU2Fv0W6ZIt+bQP/SZo4TT1yTgU/Xj9rma7l0D",
	"XJXVXV9sI6pbtnUHXJXSWqG+LepLi3OSYwqJt+44OC1HoXIUcgHeRZOaEYptWnQvr4W6W+tBQNKcEZ5R",
	"rZmUqa07zNGMfHkmdODzn4IbLvQEBlVmTJ/IO4SC3Jowu45cS5qTcvoW+53aOufF5vL/oQsS7pNI+Pvk",
	"DaJHVd4gqlwW3nLd/kmCD5MX+EgViNvswDLZ6HGfjIfd0vp65bpsOu0tpQrNU65pzL0yrvQfdLR40BRp",
	"Lkm6H2mbRTCgRuse1JuDFPM55taHaMr+GIZotYFOH1ol+0sH81yrpj3SrqXLjdxyHCfaMl6AQCFQNMUo",
	"Z9ktkXJc1aHXIpAP51H5Ty8x7lGE1DFJVchRutX6F19vdeRtWdTLQFzfZouSmg2JjNO3X0ci38VyPLRb",
	"F1NO47svZWIfZ6Zi3eP7yzgn06SsiUS2uN0lzXlBEhVNpZmYlP+A8LdCJb56uZQ/6tJHnaxXaLa42kyK",
	"C5+f5Hn5G0rwLU7QowWZLwYoxREp0gFKsqVXnEYOcnrEkUpcur3EfBszP6EpXhBp8i4wasWFNh9rCdnA",
	"3bi77BdfdTfHYcGIWF1KwDXeTnPyDq9OC2/vkIs3KMYrhftpkcSagemmRujRBcvCguH3mHL04uq9xCCR",
	"Xy0w6LCGbjAQ/HPvPf5KwozuneZk7x1eVbsDtbjE1zMMDDMLxlT966Ul4Lf/uAqaSqQcKpWDGH18c/Yc",
	"vf3HFRJZjPVFgSglFIEZEpZROLVtyazU/BUcCyFyXViXxQT7kfExh98KbKZ+9vJlVVeiPtKOtghNV+jX",
	"/dvxvhq3L0HYDyFJphDGvw6v6Wsh8o80WQ3QpTwLPECXkOJLIvDf3sPXITpV02Maqf46HEEY4lygF2+u",
	"Xr/4pCKi19Qs+PET+lWCmjHyv9QOT5DGIlI9scKbpdDNsX79N5UCkazUncuUpCk45vLiXVPzjUaeyNCS",
	"UN0bRx2mXqs6TLWtSWVUtA7yqmCUC5LgKzmhhxaTrIhmCTCMyqGSqKtohzlGlqUoTAimYo+TCKMlieZY",
	"dF+ycrY9vXILtrVK6Z5lipkSobr+mJuJnkEYYxqh04s3OozLTb+/4Wg4UhE2aX7mJDgJDoej4aHymhoz",
	"cH+BIdE3RgLY3vEChzEiM1PswW5JqOrWISG3WMVWjG2j3OUZYlpx4zo3WuuMbyKVNiJe66UkoTu+nYPR",
	"qKHYmbwP+en+jSmxLHsdfSszVIMsVsJW8bG2yKkSWas+SVkc9FC91622bpeNjWt+ZMMTwXtyi6lkKznL",
	"psqRAXMuOZ1B7hc5fF+rvrsiWn2l2shpYhIMZlLrfGQb2ahD+IQjwqXuS3Gou8zppVePfQfxSUFy33Mo",
	"O+lIQlMLK2OcSVAafyuPTONgw6lVk/oiFHrqzqxYf6Rol9Mt4TseHT4oNiLCvQiRqscPjRSaCYuV2p2X",
	"d4hsv/S3433jDd9XPvn96WpPrr3/rbQK1g5NtK6qYxLwZ6srHePLgUGKdfDls0vftYp8xWolo6sYrRso",
	"rDQSrVBXyN/JRFkPHAAORmZZHVsp19XRHneN0sEkPyl9QmNjnm7wCjmrdSyWzWYcd6zmTu9ry/jlvkzB",
	"BHs+N/ppBUfH+xckGl4WfO/q4t3+wejgcP/iw/BtLIYXvExGMvDUjtFtehVcYDqHiCRAbWM69BZiYALQ",
	"RcGVodTsERU8KyKCLoGKjGeBLhsJRuPXH578/e2786N/Xvz3fxw+O/509fzsxctXrz8E9RZFwTucQwLo",
	"jFDg6OKXi09ujz2KGUkB8QJyFAEjKM6oYBCLjKGCiiLWjfWAzmOgSCjjSNLLCsfoBhKgw0Ci3ES1xuu+",
	"t9AXoPPQsG5vN10hm2pztOtxmjqE4CLBqvPPIsukxEG3kBCTSyHnHgaNwoSj0aj3ZnQJhAf8N7SxTIMF",
	"vcI2p9JusWJCNgTXwYWqmKmX8Rj8OrznFRabGE+csSLnxJ4toTMGXLAiFgUL/GRq/9nNh+qOqy1+qxpn",
	"ON6ZDY3vzoY02L71bIjav2RXkHozQ28sUUv9uCMH/4vp/ZmY3qXTOYb/cZme5lDWnmpwPo2KWpMc7mV+",
	"gyDPeC8GZzgR5uJZps2U/ggzySzHZbpKEAMvONrEFfVVQBFWvWlTYPFekaMFsDmgLMELlOMbmIJAUXkJ",
	"A0/Si2Qid7tBFq/rJgte/4jswNcvtGqu1SbYoO3JPjwemf+td2cwbi/R+ngaQYwuSAQU0Dt94EGrmWgg",
	"N7s3ero3/iloOfWPDzY57bWYuD+DazfjNB04a/02Pwe69/H4AC0KVswQOM220U0m/3Uw2j8YjcbBlz8v",
	"17wbt/GrWlUnzX523qXbevOerqKuVp31NFu4nZeZEU+eDI/VdZcLHD8dNZNY3bFHT4cH5dijg+N1s+fn",
	"+OB41N3ls4o0nPw0GthwxMl4/HS07n2+HS1OfUdc4dWvR9ebnvY83m+mCVlfK36TFr2ZfjvMeRJtVKJz",
	"EAIz+e3//Dza+/l07/Xbd+cfLvau/r73H1++HTxZ/4vHJfggGmGrqfRfAuD3FQC15s2gH1PYleWvv5Mg",
	"afRqroizbO1fFyF9RcZWEfUOpkUOAlP0z43i6uIKncNNgd7CCoZBrTFzFWmsQqqtZopPj9b9mVqzWL7D",
	"t4GiqljgaHR0Ny1ftwvOhO4y2dbpj+6v0z+vL9HBfe1merBeNyNn/1tV47feD02em2EPHnZsM+Fs5UeZ",
	"xbaJM8slJruy51rtYS83x5OjDl58R8PETeo76C9SO9sYfw9rod45+HOj79TnL/UWUpatHCBYgUCPxo8d",
	"tiIZSbmwfpNEEMmdObYPk1iD6zXEJEWvdc7REJ1jHpO8kFzEsBuIIAFphSUQFyjHTEAKKIaEDFCsHhep",
	"nhRZgXqdTJB0WiSSF3GgcxBIPTQyHA4te075fDIaHQVuy6kq9bBKhbKxz7mtgXPqbXtcRafzlBQ7R3uj",
	"w73x8dV4dHI0OhmN/kMVBdaxrCXHq9dvfnqqseiivIbVtyQGFBMhGXJCFiBQzjDHEaZIYixF2vTlmBU5",
	"DFBeiIIDReen6EM2ROODJ2P0zmoB+wej8bFk4lPM1FstOdCoAIqmsFhCC3HHXYhz88W+J+4OJe6+tBtS",
	"P70XaXXzeDf9HlnO1uSfdspm64l7MNEoW9Ikg2g/j2adau2ZGWT46MXZyx+ZgfbmUGbL1exlJtqUUF0o",
	"3lygdW4XZy+RqiIcmFQHte5zveDeGeFuW/AKRyAEhAupoP2b+lxi4W/X9fTTLXgc5tHsOqj5glvQ1q+P",
	"PcZ64rnUjtSB3uMWOTUmXU44am/PeZls+2cTwRXnfAZzIKm0EkphVJNCUuucYwoEzZRbZE//n5YuqXoa",
	"C6jWdLWMGqgviBI1hBJXZNG5FEzUyi26gn8Pmpm9ZULuDr6UVs3Y99AIWgVQn/3i6uzFy6PjJ0GHhnB8",
	"iN798vqirhNcabU+Bk4WCARwjSG6AqB0BUN0pmRYilOVfpBOjXGx+UQGWiDmmCVFKRaVDOujT1iVhOEY",
	"UnSDbyBWw1ZA5QkW04RIDSaR4w9GSMCioEP0GhJ16CmmBb0p4tiKTSSURQq0dD+rYQWdx4SiaSF/CXXr",
	"VYpiYBAL9abbDQgiUdCUuodB1UyTFknSJYOr9O3vJoIPj0/Gx1oEN6vYNiuNtTvw4HT473WEHTgIC4DH",
	"k6rJTYU5gyOVB/zAKFIa3t1oulsVOa96bQgn7U0/MIZV8VHTaUqjsuREPZVha0LvL1L6eFLPnU5sP6BI",
	"qUWrd8+aOXbD1Qd/+KyZDfafZvWnz56PDw67WL3Xx1Rn/M8krXJglpkDWhRxkWqiFphJ9gj5oOLXNzgB",
	"jgSWTDu1EhX51rMvRDYZ5/j3s/MOu+y8B2WMLY74IzLCwYPpDhtVg7o60EPqe+Xs7y9Zd3FRtnpkdssN",
	"rnpaeTx/NavDfbPp7kLCaWe6RUZ8rBqi/uHtVg9XdRDRajioKL/WADB458tZyLG66IVUFpVPPfD1/JOz",
	"tTvvyb/WO+TVbt34ZKTZlLfFXbNXppys3rfS/qXqIvn5y+Zud/6y9c/BBaYhTAsBFC2k8p0lRFQ696FW",
	"uSUzcIvQS/FbRpUcKXlQ/a3WDuDQiUB1FKaX8/504Ex49LQx0xMdI92NAXR32nMrsIIFmS+CgTeu4ZRG",
	"eV9drsdNJEnTlWSB8gZJbrnESxWxCXaKhvgbIXvYjRnyIIER27ywDFyYrgg2WPDwcZKPzRU9DLNq6lxJ",
	"0/55TxaVfxwGeEe3S6sF906JUh3NwdfG2/HdmHKrjNPQE1BNUSYxjK5wgrWLx4Qg2u9T+iKnn3J0PBqh",
	"m0JAZwA1aD3Rv0MgV2pbrR2U9O+QP1K5bUC3wT23fMOML8GmcxAFk+JJz7cF+EPXMFjfVfZZT00z/vMp",
	"RwcD+5i8X0A6T/PVLJrBrikSLXSdZ1HBkSJzGpFGJqHuwRDXHjft2G09O1HHbzyP5Knz0dx+ihmXZztA",
	"T7SIlFfzRt7GtV8fCOrmxBSz0tC4zeRfOJ4CiekKUETQFJawQMdm6srV2UO5Dh5U8/hWvWd/EjxTW1dN",
	"H2aYIZX10cxnizFiOMa6Eb+BtvkUvmMGVu//B/p1/8D3dn/DEl639aEanFd3czxK/LdBdUwQB9g0ixSG",
	"/eCWEDr6WQ3Cdw0qcoOmSneYyi2kudTIIIIaOTYLDB4EtTb8uf6uauQgOJcbWQFDheRcueLkVJAGG/lL",
	"3Wyomy8dt43r9Rb3UENLOfR91dGq6XdToTMvijQf6LiH+aub4XgTYVqNFXTgWCwwuiki/Xq409VJ9TWp",
	"euuUes/wmp4mSbbktr2TyCo7HiNIMzrnQk6bcpzcYo6IZDKQqKacuj69EQk0Pap0lqSF/M+dj7NDCrO3",
	"g9edIm8CfxX7qknSnj5Yb+it6XZyO1PVOirtuIWqc5cvPffyhX30MZvVkxkakQU9qMyHeMDEB0M75unL",
	"btK5bL5KagmcozGSeph9TuBfyx74Q3S1ILxsDnFN9Vq88QiBbieSmld8KvqybafUAAPfNa15z9TF2kpd",
	"b8ze/qg+rz/RDa7O2Rxo14MU97/RnlyM5o2mEYIyYGeahksodXuv8lSavPxqgVHGwgXmgoFQb1jrhz0x",
	"R8sFCRd6gkf8MeKLrEjKhhloChxHKKPX1M1LGDgvVeqXdyUsuq8a1xd9Km2xcLsg+a+QVKItqve6ydoA",
	"Qe4Eb05pJJUiKqSiow0sE+6Sv2pLWmfrEUo8+SG2dduONPIQGSLbqLyJgEul8Hv2r8MsNfJvdPdzWxmW",
	"GZrfjy2wSl30sAR798tRPYjffcPDG/B4T7iNeFy6T3HUaKLRMFL19kbTVdkoqXzqz8lXs71IvbXP5Su4",
	"JR7v2sP0rxYTtbtff/zF1J7KPRqo1Kq6TO7guPbGy+fmO6nuk//N59Ia72l3lubsHECS1A9LC0TlqHAL",
	"WiTZNh5W9Ye4TQh1Ox93Ugy+tJ4TVX+yLWnK6+m+p7khwP4QGK1K7DwIxTlOSaISpCmwOBMkBnSDlcMM",
	"pkUnQk8XKUToNYlgBcJitPbgbbWro6vxcYVTP96PrkY/V56zHnh/uxPeXW7gR70L5A6hau8LTN6WP3qM",
	"L1Yt5/D2Zt5Wd96wuRVieUefZ/uGnC5G1GsPr+k1fbZChr/od7WsFYEYFgWjHL29/PgBwUzybGkgqBKy",
	"UqtUeuQ1tbKlfKq+9EoMUflUmVFJkImf8Gv666lqvHWCWjL514Fu1gUpriyhWZItkbyZagiOEHB0efni",
	"5JrqZ+Vz8+D8oGrBZz4dGLAVuEi16uVa+wM0I1TaO8YKkl8pQKRRhRH+qt/Luqa/3sXM+7VCZwgKC9Ra",
	"Zw1zrIZQ7tM/9fnWhe19Ogs0whReXjlAFx8u0assyZQ3983f90E7TP1VbgMUEesvs8lNscoK1YmjKNel",
	"jJaPC8xiIKI7KMIxJQko9+XYei+H6C3EXIVwSt9cfVHXQ8exdvq68ammT92tv9ta/Se1Gjwt5P2ogkms",
	"yJXvb4MnPAUOKMbsxs20feer9il9jca9XvPdIojJFEQjFhMBRXEBCRHAUQoCM3mX9GymSokXQBDPMScz",
	"EgMnw001sZtEjfMcdfXWz841p80C2oOqgLZ/xYuiiPLl2e+XNW6Iszsp+K9MwvtkEvbWB8s3wHapAB74",
	"4rRfms+B7VjvfeDWe3tfBispgfAOEsjCUDJOE8xu8Vln/fqLYZ+D8xqL28DagkFwXmMUmokFg+Bdi1t0",
	"MQqnF0f/aLaPcd/h8rR0urvyBscw3mb/1wx6C6/RWr+j7fKDoayP88FVsnCEeBGGmPNZkSSrezWHcjUT",
	"lBZcoClGIFCCgQt0PEKSD0Ao9MOc369PVK1BlOmQrSzdZi9jHZB26iYVRhDFy643V3p7XmrapZa16omI",
	"ds2k+ntLPfxTZp+WctgChDRW2newq+2rI8nv1MC1tmrDntMnsfGwB9vSh//kB+i87v/wXqN+WsJ/IRXg",
	"3cacsocU71udbz0Myof3z+lErDI7Ulca/m51QS31vVtx/xG1dY+n7cESEFudbX46KFcjQr1wxDV9bs8y",
	"tGa3SmG01nKZeuhMysOM4eBkNHz6U0dKYiMFqMpNjIgOfflyFHfz+e5aWvkKi7Zuu0FO3T9l3Ura79vO",
	"57K1SjtNnTd2dVdtat96hTc29FEj/pLKP3YspyPycHw1PqiiCv+JEuXe4QgX8u/FFSooWl1f1N93sF2U",
	"oGG3/oDv+yyEBEX4FidZrhJ0B0HBEvO8zsn+fiIHLDIuTp6ORqNg/WX9/wMAAP//wL68gcW2AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
