"""
Council Database Package

This package provides typed database query functions generated by SQLC.
Both Go and Python use the same SQL queries from internal/db/queries/council.sql.

Regenerate with: make sqlc-generate

Usage:
    from sqlalchemy.ext.asyncio import create_async_engine, AsyncConnection
    from src.council.db.sqlc import CouncilQuerier, ExtractionQuerier

    engine = create_async_engine(dsn)
    async with engine.connect() as conn:
        querier = CouncilQuerier(conn)
        session = await querier.get_council_session(id="...")
"""

# Re-export SQLC generated code
from .sqlc import (
    # Council querier
    CouncilQuerier,
    CouncilV1DeliberationMessage,
    CouncilV1DeliberationSession,
    CreateCouncilMessageParams,
    CreateCouncilSessionParams,
    # Extraction querier
    ExtractionQuerier,
    FindSimilarCasesByEmbeddingRow,
    FindSimilarCasesByEmbeddingWithFilterRow,
    GetCaseTypeDistributionRow,
    GetLLMExtractionByIDRow,
    GetSentenceStatsByCategoryRow,
    GetSessionsWithMessageCountsRow,
    GetVerdictDistributionRow,
    TextSearchCasesRow,
    UpdateCouncilSessionParams,
)

__all__ = [
    # Council Querier
    "CouncilQuerier",
    # Council Models
    "CouncilV1DeliberationMessage",
    "CouncilV1DeliberationSession",
    # Council Params
    "CreateCouncilMessageParams",
    "CreateCouncilSessionParams",
    "GetSessionsWithMessageCountsRow",
    "UpdateCouncilSessionParams",
    # Extraction Querier
    "ExtractionQuerier",
    # Extraction Row types
    "FindSimilarCasesByEmbeddingRow",
    "FindSimilarCasesByEmbeddingWithFilterRow",
    "GetCaseTypeDistributionRow",
    "GetLLMExtractionByIDRow",
    "GetSentenceStatsByCategoryRow",
    "GetVerdictDistributionRow",
    "TextSearchCasesRow",
]
