# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: council.sql
import datetime
from collections.abc import AsyncIterator
from typing import Any

import pydantic
import sqlalchemy
import sqlalchemy.ext.asyncio

from . import models

CONCLUDE_COUNCIL_SESSION = """-- name: conclude_council_session \\:one
UPDATE council_v1.deliberation_sessions
SET
    status = 'concluded',
    concluded_at = NOW(),
    updated_at = NOW()
WHERE id = :p1
RETURNING id, user_id, status, case_input, similar_cases, legal_opinion, created_at, updated_at, concluded_at, current_phase, phase_metadata, structured_summary
"""


COUNT_COUNCIL_SESSIONS = """-- name: count_council_sessions \\:one
SELECT COUNT(*) FROM council_v1.deliberation_sessions
WHERE
    (:p1\\:\\:varchar IS NULL OR user_id = :p1)
    AND (:p2\\:\\:varchar IS NULL OR status = :p2)
"""


CREATE_COUNCIL_MESSAGE = """-- name: create_council_message \\:one

INSERT INTO council_v1.deliberation_messages (
    id, session_id, sender, content, intent, cited_cases, cited_laws, sequence_number, timestamp
) VALUES (
    :p1, :p2, :p3, :p4, :p5, :p6, :p7, :p8, NOW()
)
RETURNING id, session_id, sender, content, intent, cited_cases, cited_laws, sequence_number, timestamp
"""


class CreateCouncilMessageParams(pydantic.BaseModel):
    id: str
    session_id: str
    sender: Any
    content: str
    intent: str | None
    cited_cases: Any
    cited_laws: Any
    sequence_number: int


CREATE_COUNCIL_SESSION = """-- name: create_council_session \\:one


INSERT INTO council_v1.deliberation_sessions (
    id, user_id, status, case_input, similar_cases, legal_opinion, created_at, updated_at
) VALUES (
    :p1, :p2, :p3, :p4, :p5, :p6, NOW(), NOW()
)
RETURNING id, user_id, status, case_input, similar_cases, legal_opinion, created_at, updated_at, concluded_at, current_phase, phase_metadata, structured_summary
"""


class CreateCouncilSessionParams(pydantic.BaseModel):
    id: str
    user_id: str | None
    status: str
    case_input: Any
    similar_cases: Any
    legal_opinion: Any | None


DELETE_COUNCIL_SESSION = """-- name: delete_council_session \\:exec
DELETE FROM council_v1.deliberation_sessions
WHERE id = :p1
"""


DELETE_MESSAGES_FOR_SESSION = """-- name: delete_messages_for_session \\:exec
DELETE FROM council_v1.deliberation_messages
WHERE session_id = :p1
"""


GET_COUNCIL_SESSION = """-- name: get_council_session \\:one
SELECT id, user_id, status, case_input, similar_cases, legal_opinion, created_at, updated_at, concluded_at, current_phase, phase_metadata, structured_summary FROM council_v1.deliberation_sessions
WHERE id = :p1
"""


GET_COUNCIL_SESSION_WITH_MESSAGES = """-- name: get_council_session_with_messages \\:many
SELECT
    m.id,
    m.session_id,
    m.sender,
    m.content,
    m.intent,
    m.cited_cases,
    m.cited_laws,
    m.sequence_number,
    m.timestamp
FROM council_v1.deliberation_messages m
WHERE m.session_id = :p1
ORDER BY m.sequence_number ASC
"""


GET_LATEST_MESSAGE_SEQUENCE = """-- name: get_latest_message_sequence \\:one
SELECT COALESCE(MAX(sequence_number), -1) FROM council_v1.deliberation_messages
WHERE session_id = :p1
"""


GET_MESSAGE_COUNT_FOR_SESSION = """-- name: get_message_count_for_session \\:one
SELECT COUNT(*) FROM council_v1.deliberation_messages
WHERE session_id = :p1
"""


GET_MESSAGES_FOR_SESSION = """-- name: get_messages_for_session \\:many
SELECT id, session_id, sender, content, intent, cited_cases, cited_laws, sequence_number, timestamp FROM council_v1.deliberation_messages
WHERE session_id = :p1
ORDER BY sequence_number ASC, id DESC
LIMIT :p3
OFFSET :p2
"""


GET_MESSAGES_FOR_SESSIONS = """-- name: get_messages_for_sessions \\:many
SELECT id, session_id, sender, content, intent, cited_cases, cited_laws, sequence_number, timestamp FROM council_v1.deliberation_messages
WHERE session_id = ANY(:p1\\:\\:varchar[])
ORDER BY session_id, sequence_number ASC
"""


GET_SESSION_PHASE_STATE = """-- name: get_session_phase_state \\:one

SELECT id, current_phase, phase_metadata
FROM council_v1.deliberation_sessions
WHERE id = :p1
"""


class GetSessionPhaseStateRow(pydantic.BaseModel):
    id: str
    current_phase: str
    phase_metadata: Any


GET_SESSIONS_WITH_MESSAGE_COUNTS = """-- name: get_sessions_with_message_counts \\:many

SELECT
    s.id, s.user_id, s.status, s.case_input, s.similar_cases, s.legal_opinion, s.created_at, s.updated_at, s.concluded_at, s.current_phase, s.phase_metadata, s.structured_summary,
    COUNT(m.id) as message_count
FROM council_v1.deliberation_sessions s
LEFT JOIN council_v1.deliberation_messages m ON m.session_id = s.id
WHERE
    (:p1\\:\\:varchar IS NULL OR s.user_id = :p1)
    AND (:p2\\:\\:varchar IS NULL OR s.status = :p2)
GROUP BY s.id
ORDER BY s.created_at DESC, s.id DESC
LIMIT :p4
OFFSET :p3
"""


class GetSessionsWithMessageCountsRow(pydantic.BaseModel):
    id: str
    user_id: str | None
    status: str
    case_input: Any
    similar_cases: Any
    legal_opinion: Any | None
    created_at: datetime.datetime
    updated_at: datetime.datetime
    concluded_at: datetime.datetime | None
    current_phase: str
    phase_metadata: Any
    structured_summary: Any | None
    message_count: int


LIST_COUNCIL_SESSIONS = """-- name: list_council_sessions \\:many
SELECT id, user_id, status, case_input, similar_cases, legal_opinion, created_at, updated_at, concluded_at, current_phase, phase_metadata, structured_summary FROM council_v1.deliberation_sessions
WHERE
    (:p1\\:\\:varchar IS NULL OR user_id = :p1)
    AND (:p2\\:\\:varchar IS NULL OR status = :p2)
ORDER BY created_at DESC, id DESC
LIMIT :p4
OFFSET :p3
"""


LOCK_COUNCIL_SESSION = """-- name: lock_council_session \\:one

SELECT id FROM council_v1.deliberation_sessions
WHERE id = :p1
FOR UPDATE
"""


TOUCH_COUNCIL_SESSION = """-- name: touch_council_session \\:exec
UPDATE council_v1.deliberation_sessions
SET updated_at = NOW()
WHERE id = :p1
"""


UPDATE_COUNCIL_SESSION = """-- name: update_council_session \\:exec
UPDATE council_v1.deliberation_sessions
SET
    status = :p2,
    case_input = :p3,
    similar_cases = :p4,
    legal_opinion = :p5,
    updated_at = NOW(),
    concluded_at = :p6
WHERE id = :p1
"""


class UpdateCouncilSessionParams(pydantic.BaseModel):
    id: str
    status: str
    case_input: Any
    similar_cases: Any
    legal_opinion: Any | None
    concluded_at: datetime.datetime | None


UPDATE_COUNCIL_SESSION_SIMILAR_CASES = """-- name: update_council_session_similar_cases \\:exec
UPDATE council_v1.deliberation_sessions
SET
    similar_cases = :p2,
    updated_at = NOW()
WHERE id = :p1
"""


UPDATE_SESSION_PHASE = """-- name: update_session_phase \\:exec
UPDATE council_v1.deliberation_sessions
SET
    current_phase = :p1,
    phase_metadata = :p2,
    updated_at = NOW()
WHERE id = :p3 AND current_phase = :p4
"""


UPDATE_SESSION_PHASE_METADATA = """-- name: update_session_phase_metadata \\:exec
UPDATE council_v1.deliberation_sessions
SET
    phase_metadata = :p2,
    updated_at = NOW()
WHERE id = :p1
"""


UPDATE_SESSION_STRUCTURED_SUMMARY = """-- name: update_session_structured_summary \\:exec
UPDATE council_v1.deliberation_sessions
SET
    structured_summary = :p2,
    updated_at = NOW()
WHERE id = :p1
"""


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def conclude_council_session(
        self, *, id: str
    ) -> models.CouncilV1DeliberationSession | None:
        row = (
            await self._conn.execute(
                sqlalchemy.text(CONCLUDE_COUNCIL_SESSION), {"p1": id}
            )
        ).first()
        if row is None:
            return None
        return models.CouncilV1DeliberationSession(
            id=row[0],
            user_id=row[1],
            status=row[2],
            case_input=row[3],
            similar_cases=row[4],
            legal_opinion=row[5],
            created_at=row[6],
            updated_at=row[7],
            concluded_at=row[8],
            current_phase=row[9],
            phase_metadata=row[10],
            structured_summary=row[11],
        )

    async def count_council_sessions(
        self, *, user_id: str | None, status: str | None
    ) -> int | None:
        row = (
            await self._conn.execute(
                sqlalchemy.text(COUNT_COUNCIL_SESSIONS), {"p1": user_id, "p2": status}
            )
        ).first()
        if row is None:
            return None
        return row[0]

    async def create_council_message(
        self, arg: CreateCouncilMessageParams
    ) -> models.CouncilV1DeliberationMessage | None:
        row = (
            await self._conn.execute(
                sqlalchemy.text(CREATE_COUNCIL_MESSAGE),
                {
                    "p1": arg.id,
                    "p2": arg.session_id,
                    "p3": arg.sender,
                    "p4": arg.content,
                    "p5": arg.intent,
                    "p6": arg.cited_cases,
                    "p7": arg.cited_laws,
                    "p8": arg.sequence_number,
                },
            )
        ).first()
        if row is None:
            return None
        return models.CouncilV1DeliberationMessage(
            id=row[0],
            session_id=row[1],
            sender=row[2],
            content=row[3],
            intent=row[4],
            cited_cases=row[5],
            cited_laws=row[6],
            sequence_number=row[7],
            timestamp=row[8],
        )

    async def create_council_session(
        self, arg: CreateCouncilSessionParams
    ) -> models.CouncilV1DeliberationSession | None:
        row = (
            await self._conn.execute(
                sqlalchemy.text(CREATE_COUNCIL_SESSION),
                {
                    "p1": arg.id,
                    "p2": arg.user_id,
                    "p3": arg.status,
                    "p4": arg.case_input,
                    "p5": arg.similar_cases,
                    "p6": arg.legal_opinion,
                },
            )
        ).first()
        if row is None:
            return None
        return models.CouncilV1DeliberationSession(
            id=row[0],
            user_id=row[1],
            status=row[2],
            case_input=row[3],
            similar_cases=row[4],
            legal_opinion=row[5],
            created_at=row[6],
            updated_at=row[7],
            concluded_at=row[8],
            current_phase=row[9],
            phase_metadata=row[10],
            structured_summary=row[11],
        )

    async def delete_council_session(self, *, id: str) -> None:
        await self._conn.execute(sqlalchemy.text(DELETE_COUNCIL_SESSION), {"p1": id})

    async def delete_messages_for_session(self, *, session_id: str) -> None:
        await self._conn.execute(
            sqlalchemy.text(DELETE_MESSAGES_FOR_SESSION), {"p1": session_id}
        )

    async def get_council_session(
        self, *, id: str
    ) -> models.CouncilV1DeliberationSession | None:
        row = (
            await self._conn.execute(sqlalchemy.text(GET_COUNCIL_SESSION), {"p1": id})
        ).first()
        if row is None:
            return None
        return models.CouncilV1DeliberationSession(
            id=row[0],
            user_id=row[1],
            status=row[2],
            case_input=row[3],
            similar_cases=row[4],
            legal_opinion=row[5],
            created_at=row[6],
            updated_at=row[7],
            concluded_at=row[8],
            current_phase=row[9],
            phase_metadata=row[10],
            structured_summary=row[11],
        )

    async def get_council_session_with_messages(
        self, *, session_id: str
    ) -> AsyncIterator[models.CouncilV1DeliberationMessage]:
        result = await self._conn.stream(
            sqlalchemy.text(GET_COUNCIL_SESSION_WITH_MESSAGES), {"p1": session_id}
        )
        async for row in result:
            yield models.CouncilV1DeliberationMessage(
                id=row[0],
                session_id=row[1],
                sender=row[2],
                content=row[3],
                intent=row[4],
                cited_cases=row[5],
                cited_laws=row[6],
                sequence_number=row[7],
                timestamp=row[8],
            )

    async def get_latest_message_sequence(self, *, session_id: str) -> Any | None:
        row = (
            await self._conn.execute(
                sqlalchemy.text(GET_LATEST_MESSAGE_SEQUENCE), {"p1": session_id}
            )
        ).first()
        if row is None:
            return None
        return row[0]

    async def get_message_count_for_session(self, *, session_id: str) -> int | None:
        row = (
            await self._conn.execute(
                sqlalchemy.text(GET_MESSAGE_COUNT_FOR_SESSION), {"p1": session_id}
            )
        ).first()
        if row is None:
            return None
        return row[0]

    async def get_messages_for_session(
        self, *, session_id: str, offset_val: int, limit_val: int
    ) -> AsyncIterator[models.CouncilV1DeliberationMessage]:
        result = await self._conn.stream(
            sqlalchemy.text(GET_MESSAGES_FOR_SESSION),
            {"p1": session_id, "p2": offset_val, "p3": limit_val},
        )
        async for row in result:
            yield models.CouncilV1DeliberationMessage(
                id=row[0],
                session_id=row[1],
                sender=row[2],
                content=row[3],
                intent=row[4],
                cited_cases=row[5],
                cited_laws=row[6],
                sequence_number=row[7],
                timestamp=row[8],
            )

    async def get_messages_for_sessions(
        self, *, session_ids: list[str]
    ) -> AsyncIterator[models.CouncilV1DeliberationMessage]:
        result = await self._conn.stream(
            sqlalchemy.text(GET_MESSAGES_FOR_SESSIONS), {"p1": session_ids}
        )
        async for row in result:
            yield models.CouncilV1DeliberationMessage(
                id=row[0],
                session_id=row[1],
                sender=row[2],
                content=row[3],
                intent=row[4],
                cited_cases=row[5],
                cited_laws=row[6],
                sequence_number=row[7],
                timestamp=row[8],
            )

    async def get_session_phase_state(
        self, *, id: str
    ) -> GetSessionPhaseStateRow | None:
        row = (
            await self._conn.execute(
                sqlalchemy.text(GET_SESSION_PHASE_STATE), {"p1": id}
            )
        ).first()
        if row is None:
            return None
        return GetSessionPhaseStateRow(
            id=row[0],
            current_phase=row[1],
            phase_metadata=row[2],
        )

    async def get_sessions_with_message_counts(
        self,
        *,
        user_id: str | None,
        status: str | None,
        offset_val: int,
        limit_val: int,
    ) -> AsyncIterator[GetSessionsWithMessageCountsRow]:
        result = await self._conn.stream(
            sqlalchemy.text(GET_SESSIONS_WITH_MESSAGE_COUNTS),
            {
                "p1": user_id,
                "p2": status,
                "p3": offset_val,
                "p4": limit_val,
            },
        )
        async for row in result:
            yield GetSessionsWithMessageCountsRow(
                id=row[0],
                user_id=row[1],
                status=row[2],
                case_input=row[3],
                similar_cases=row[4],
                legal_opinion=row[5],
                created_at=row[6],
                updated_at=row[7],
                concluded_at=row[8],
                current_phase=row[9],
                phase_metadata=row[10],
                structured_summary=row[11],
                message_count=row[12],
            )

    async def list_council_sessions(
        self,
        *,
        user_id: str | None,
        status: str | None,
        offset_val: int,
        limit_val: int,
    ) -> AsyncIterator[models.CouncilV1DeliberationSession]:
        result = await self._conn.stream(
            sqlalchemy.text(LIST_COUNCIL_SESSIONS),
            {
                "p1": user_id,
                "p2": status,
                "p3": offset_val,
                "p4": limit_val,
            },
        )
        async for row in result:
            yield models.CouncilV1DeliberationSession(
                id=row[0],
                user_id=row[1],
                status=row[2],
                case_input=row[3],
                similar_cases=row[4],
                legal_opinion=row[5],
                created_at=row[6],
                updated_at=row[7],
                concluded_at=row[8],
                current_phase=row[9],
                phase_metadata=row[10],
                structured_summary=row[11],
            )

    async def lock_council_session(self, *, id: str) -> str | None:
        row = (
            await self._conn.execute(sqlalchemy.text(LOCK_COUNCIL_SESSION), {"p1": id})
        ).first()
        if row is None:
            return None
        return row[0]

    async def touch_council_session(self, *, id: str) -> None:
        await self._conn.execute(sqlalchemy.text(TOUCH_COUNCIL_SESSION), {"p1": id})

    async def update_council_session(self, arg: UpdateCouncilSessionParams) -> None:
        await self._conn.execute(
            sqlalchemy.text(UPDATE_COUNCIL_SESSION),
            {
                "p1": arg.id,
                "p2": arg.status,
                "p3": arg.case_input,
                "p4": arg.similar_cases,
                "p5": arg.legal_opinion,
                "p6": arg.concluded_at,
            },
        )

    async def update_council_session_similar_cases(
        self, *, id: str, similar_cases: Any
    ) -> None:
        await self._conn.execute(
            sqlalchemy.text(UPDATE_COUNCIL_SESSION_SIMILAR_CASES),
            {"p1": id, "p2": similar_cases},
        )

    async def update_session_phase(
        self, *, new_phase: str, new_metadata: Any, session_id: str, expected_phase: str
    ) -> None:
        await self._conn.execute(
            sqlalchemy.text(UPDATE_SESSION_PHASE),
            {
                "p1": new_phase,
                "p2": new_metadata,
                "p3": session_id,
                "p4": expected_phase,
            },
        )

    async def update_session_phase_metadata(
        self, *, id: str, phase_metadata: Any
    ) -> None:
        await self._conn.execute(
            sqlalchemy.text(UPDATE_SESSION_PHASE_METADATA),
            {"p1": id, "p2": phase_metadata},
        )

    async def update_session_structured_summary(
        self, *, id: str, structured_summary: Any | None
    ) -> None:
        await self._conn.execute(
            sqlalchemy.text(UPDATE_SESSION_STRUCTURED_SUMMARY),
            {"p1": id, "p2": structured_summary},
        )
