# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
import datetime
from typing import Any

import pydantic


class CouncilV1DeliberationMessage(pydantic.BaseModel):
    id: str
    session_id: str
    sender: Any
    content: str
    intent: str | None
    cited_cases: Any
    cited_laws: Any
    sequence_number: int
    timestamp: datetime.datetime


class CouncilV1DeliberationSession(pydantic.BaseModel):
    id: str
    user_id: str | None
    status: str
    case_input: Any
    similar_cases: Any
    legal_opinion: Any | None
    created_at: datetime.datetime
    updated_at: datetime.datetime
    concluded_at: datetime.datetime | None
    current_phase: str
    phase_metadata: Any
    structured_summary: Any | None
