-- ============================================================
-- event_content: summaries + heavy text content (1:1 with events)
-- ============================================================
CREATE TABLE entity_graph.event_content (
    event_id        UUID NOT NULL PRIMARY KEY REFERENCES entity_graph.events(id) ON DELETE CASCADE,
    summary         TEXT,
    summary_en      TEXT,
    body_markdown   TEXT,
    properties      JSONB NOT NULL DEFAULT '{}',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE entity_graph.event_content IS 'Summaries and heavy text content for events. 1:1 with events (optional). Separated to keep core events table lean for graph traversal.';
COMMENT ON COLUMN entity_graph.event_content.event_id IS 'FK to events.id — also serves as PK enforcing at-most-one content row per event.';
COMMENT ON COLUMN entity_graph.event_content.summary IS 'Indonesian-language summary. Generated by LLM extraction pipeline. May be NULL if not yet extracted.';
COMMENT ON COLUMN entity_graph.event_content.summary_en IS 'English-language summary. Generated by LLM extraction pipeline. May be NULL if not yet extracted.';
COMMENT ON COLUMN entity_graph.event_content.body_markdown IS 'Curated formatted content as markdown — not raw PDF text. For verdicts: structured summary with sections. For sanctions: violation description.';
COMMENT ON COLUMN entity_graph.event_content.properties IS 'Type-specific heavy content. Verdicts: {"indictment": {...}, "judicial_considerations": {...}, "sentences": {...}, ...}. Sanctions: {"reason_detail": "...", "action_description": "..."}.';

CREATE TRIGGER set_event_content_updated_at
    BEFORE UPDATE ON entity_graph.event_content
    FOR EACH ROW EXECUTE FUNCTION entity_graph.trigger_set_timestamp();
