# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: llm_extractions.sql
import datetime
from collections.abc import AsyncIterator
from typing import Any

import pydantic
import sqlalchemy
import sqlalchemy.ext.asyncio

COUNT_ALL_CASES = """-- name: count_all_cases \\:one
SELECT COUNT(*)
FROM llm_extraction.mahkamah_agung_putusans
WHERE status = 'completed'
"""


COUNT_CASES_BY_TYPE_PATTERN = """-- name: count_cases_by_type_pattern \\:one
SELECT COUNT(*)
FROM llm_extraction.mahkamah_agung_putusans
WHERE status = 'completed'
AND (
    extraction_result->'case_metadata'->>'crime_category' ILIKE :p1\\:\\:text
    OR extraction_result->>'crime_category' ILIKE :p1\\:\\:text
)
"""


COUNT_COMPLETED_LLM_EXTRACTIONS = """-- name: count_completed_llm_extractions \\:one
SELECT COUNT(*)
FROM llm_extraction.mahkamah_agung_putusans
WHERE embedding_generated = true AND status = 'completed'
"""


FIND_SIMILAR_CASES_BY_EMBEDDING = """-- name: find_similar_cases_by_embedding \\:many
SELECT
    extraction_id,
    summary_id,
    summary_en,
    extraction_result,
    (1 - (content_embedding <=> :p1\\:\\:vector))\\:\\:float8 as similarity
FROM llm_extraction.mahkamah_agung_putusans
WHERE content_embedding IS NOT NULL
AND status = 'completed'
ORDER BY similarity DESC
LIMIT :p2
"""


class FindSimilarCasesByEmbeddingRow(pydantic.BaseModel):
    extraction_id: str
    summary_id: str | None
    summary_en: str | None
    extraction_result: Any | None
    similarity: float


FIND_SIMILAR_CASES_BY_EMBEDDING_WITH_FILTER = """-- name: find_similar_cases_by_embedding_with_filter \\:many
SELECT
    extraction_id,
    summary_id,
    summary_en,
    extraction_result,
    (1 - (content_embedding <=> :p1\\:\\:vector))\\:\\:float8 as similarity
FROM llm_extraction.mahkamah_agung_putusans
WHERE content_embedding IS NOT NULL
AND status = 'completed'
AND (
    extraction_result->>'crime_category' ILIKE ANY(:p3\\:\\:text[])
    OR extraction_result->'case_metadata'->>'crime_category' ILIKE ANY(:p3\\:\\:text[])
)
ORDER BY similarity DESC
LIMIT :p2
"""


class FindSimilarCasesByEmbeddingWithFilterRow(pydantic.BaseModel):
    extraction_id: str
    summary_id: str | None
    summary_en: str | None
    extraction_result: Any | None
    similarity: float


GET_ALL_CASES = """-- name: get_all_cases \\:many
SELECT
    extraction_id,
    summary_id,
    summary_en,
    extraction_result
FROM llm_extraction.mahkamah_agung_putusans
WHERE status = 'completed'
ORDER BY created_at DESC
LIMIT :p1 OFFSET :p2
"""


class GetAllCasesRow(pydantic.BaseModel):
    extraction_id: str
    summary_id: str | None
    summary_en: str | None
    extraction_result: Any | None


GET_CASE_TYPE_DISTRIBUTION = """-- name: get_case_type_distribution \\:many
SELECT
    COALESCE(
        extraction_result->'case_metadata'->>'crime_category',
        extraction_result->>'crime_category',
        'Unknown'
    ) as crime_category,
    COUNT(*) as case_count
FROM llm_extraction.mahkamah_agung_putusans
WHERE status = 'completed'
AND extraction_result IS NOT NULL
GROUP BY crime_category
ORDER BY case_count DESC
LIMIT 20
"""


class GetCaseTypeDistributionRow(pydantic.BaseModel):
    crime_category: Any | None
    case_count: int


GET_CASES_BY_TYPE_PATTERN = """-- name: get_cases_by_type_pattern \\:many
SELECT
    extraction_id,
    summary_id,
    summary_en,
    extraction_result
FROM llm_extraction.mahkamah_agung_putusans
WHERE status = 'completed'
AND (
    extraction_result->'case_metadata'->>'crime_category' ILIKE :p1\\:\\:text
    OR extraction_result->>'crime_category' ILIKE :p1\\:\\:text
)
ORDER BY created_at DESC
LIMIT :p3 OFFSET :p2
"""


class GetCasesByTypePatternRow(pydantic.BaseModel):
    extraction_id: str
    summary_id: str | None
    summary_en: str | None
    extraction_result: Any | None


GET_LLM_EXTRACTION_BY_ID = """-- name: get_llm_extraction_by_id \\:one

SELECT
    extraction_id,
    extraction_result,
    summary_en,
    summary_id,
    status,
    created_at
FROM llm_extraction.mahkamah_agung_putusans
WHERE extraction_id = :p1
AND status = 'completed'
"""


class GetLLMExtractionByIDRow(pydantic.BaseModel):
    extraction_id: str
    extraction_result: Any | None
    summary_en: str | None
    summary_id: str | None
    status: str
    created_at: datetime.datetime


GET_SENTENCE_STATS_BY_CATEGORY = """-- name: get_sentence_stats_by_category \\:many
SELECT
    COALESCE(
        extraction_result->'case_metadata'->>'crime_category',
        extraction_result->>'crime_category',
        'Unknown'
    ) as category,
    AVG(
        COALESCE(
            (extraction_result->'verdict'->'sentences'
                ->'imprisonment'->>'duration_months')\\:\\:float,
            (extraction_result->'verdict'->'sentences'
                ->'imprisonment'->>'duration_years')\\:\\:float * 12,
            0
        )
    ) as avg_months,
    COUNT(*) as case_count
FROM llm_extraction.mahkamah_agung_putusans
WHERE status = 'completed'
AND extraction_result IS NOT NULL
GROUP BY category
HAVING COUNT(*) >= 3
ORDER BY case_count DESC
LIMIT 10
"""


class GetSentenceStatsByCategoryRow(pydantic.BaseModel):
    category: Any | None
    avg_months: float
    case_count: int


GET_VERDICT_DISTRIBUTION = """-- name: get_verdict_distribution \\:many
SELECT
    COALESCE(
        extraction_result->'verdict'->>'result',
        'Unknown'
    ) as verdict_result,
    COUNT(*) as case_count
FROM llm_extraction.mahkamah_agung_putusans
WHERE status = 'completed'
AND extraction_result IS NOT NULL
GROUP BY verdict_result
ORDER BY case_count DESC
"""


class GetVerdictDistributionRow(pydantic.BaseModel):
    verdict_result: Any | None
    case_count: int


TEXT_SEARCH_CASES = """-- name: text_search_cases \\:many
SELECT
    extraction_id,
    summary_id,
    summary_en,
    extraction_result
FROM llm_extraction.mahkamah_agung_putusans
WHERE status = 'completed'
AND (
    summary_id ILIKE :p1
    OR summary_en ILIKE :p1
)
ORDER BY created_at DESC
LIMIT :p2
"""


class TextSearchCasesRow(pydantic.BaseModel):
    extraction_id: str
    summary_id: str | None
    summary_en: str | None
    extraction_result: Any | None


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def count_all_cases(self) -> int | None:
        row = (await self._conn.execute(sqlalchemy.text(COUNT_ALL_CASES))).first()
        if row is None:
            return None
        return row[0]

    async def count_cases_by_type_pattern(self, *, type_pattern: str) -> int | None:
        row = (
            await self._conn.execute(
                sqlalchemy.text(COUNT_CASES_BY_TYPE_PATTERN), {"p1": type_pattern}
            )
        ).first()
        if row is None:
            return None
        return row[0]

    async def count_completed_llm_extractions(self) -> int | None:
        row = (
            await self._conn.execute(sqlalchemy.text(COUNT_COMPLETED_LLM_EXTRACTIONS))
        ).first()
        if row is None:
            return None
        return row[0]

    async def find_similar_cases_by_embedding(
        self, *, dollar_1: Any, limit: int
    ) -> AsyncIterator[FindSimilarCasesByEmbeddingRow]:
        result = await self._conn.stream(
            sqlalchemy.text(FIND_SIMILAR_CASES_BY_EMBEDDING),
            {"p1": dollar_1, "p2": limit},
        )
        async for row in result:
            yield FindSimilarCasesByEmbeddingRow(
                extraction_id=row[0],
                summary_id=row[1],
                summary_en=row[2],
                extraction_result=row[3],
                similarity=row[4],
            )

    async def find_similar_cases_by_embedding_with_filter(
        self, *, dollar_1: Any, limit: int, dollar_3: list[str]
    ) -> AsyncIterator[FindSimilarCasesByEmbeddingWithFilterRow]:
        result = await self._conn.stream(
            sqlalchemy.text(FIND_SIMILAR_CASES_BY_EMBEDDING_WITH_FILTER),
            {"p1": dollar_1, "p2": limit, "p3": dollar_3},
        )
        async for row in result:
            yield FindSimilarCasesByEmbeddingWithFilterRow(
                extraction_id=row[0],
                summary_id=row[1],
                summary_en=row[2],
                extraction_result=row[3],
                similarity=row[4],
            )

    async def get_all_cases(
        self, *, limit: int, offset: int
    ) -> AsyncIterator[GetAllCasesRow]:
        result = await self._conn.stream(
            sqlalchemy.text(GET_ALL_CASES), {"p1": limit, "p2": offset}
        )
        async for row in result:
            yield GetAllCasesRow(
                extraction_id=row[0],
                summary_id=row[1],
                summary_en=row[2],
                extraction_result=row[3],
            )

    async def get_case_type_distribution(
        self,
    ) -> AsyncIterator[GetCaseTypeDistributionRow]:
        result = await self._conn.stream(sqlalchemy.text(GET_CASE_TYPE_DISTRIBUTION))
        async for row in result:
            yield GetCaseTypeDistributionRow(
                crime_category=row[0],
                case_count=row[1],
            )

    async def get_cases_by_type_pattern(
        self, *, type_pattern: str, offset_val: int, limit_val: int
    ) -> AsyncIterator[GetCasesByTypePatternRow]:
        result = await self._conn.stream(
            sqlalchemy.text(GET_CASES_BY_TYPE_PATTERN),
            {"p1": type_pattern, "p2": offset_val, "p3": limit_val},
        )
        async for row in result:
            yield GetCasesByTypePatternRow(
                extraction_id=row[0],
                summary_id=row[1],
                summary_en=row[2],
                extraction_result=row[3],
            )

    async def get_llm_extraction_by_id(
        self, *, extraction_id: str
    ) -> GetLLMExtractionByIDRow | None:
        row = (
            await self._conn.execute(
                sqlalchemy.text(GET_LLM_EXTRACTION_BY_ID), {"p1": extraction_id}
            )
        ).first()
        if row is None:
            return None
        return GetLLMExtractionByIDRow(
            extraction_id=row[0],
            extraction_result=row[1],
            summary_en=row[2],
            summary_id=row[3],
            status=row[4],
            created_at=row[5],
        )

    async def get_sentence_stats_by_category(
        self,
    ) -> AsyncIterator[GetSentenceStatsByCategoryRow]:
        result = await self._conn.stream(
            sqlalchemy.text(GET_SENTENCE_STATS_BY_CATEGORY)
        )
        async for row in result:
            yield GetSentenceStatsByCategoryRow(
                category=row[0],
                avg_months=row[1],
                case_count=row[2],
            )

    async def get_verdict_distribution(
        self,
    ) -> AsyncIterator[GetVerdictDistributionRow]:
        result = await self._conn.stream(sqlalchemy.text(GET_VERDICT_DISTRIBUTION))
        async for row in result:
            yield GetVerdictDistributionRow(
                verdict_result=row[0],
                case_count=row[1],
            )

    async def text_search_cases(
        self, *, summary_id: str | None, limit: int
    ) -> AsyncIterator[TextSearchCasesRow]:
        result = await self._conn.stream(
            sqlalchemy.text(TEXT_SEARCH_CASES), {"p1": summary_id, "p2": limit}
        )
        async for row in result:
            yield TextSearchCasesRow(
                extraction_id=row[0],
                summary_id=row[1],
                summary_en=row[2],
                extraction_result=row[3],
            )
