# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
import datetime
import uuid
from typing import Any

import pydantic


class LlmExtractionBpkRegulation(pydantic.BaseModel):
    extraction_id: uuid.UUID
    source_id: int
    status: str
    extraction_result: Any | None
    page_count: int | None
    extraction_model: str | None
    extraction_tokens_in: int | None
    extraction_tokens_out: int | None
    error_message: str | None
    created_at: datetime.datetime
    updated_at: datetime.datetime
    confidence_score: float | None
    text_coverage: float | None
    # 1 = v1 (LLM-only), 2 = v2 (regex-first + LLM fallback)
    extraction_version: int | None
    # regex = deterministic section detection, llm_phase1 = LLM-based outline
    detection_method: str | None
    # born_digital = regex extraction, scanned_clean = LLM with OCR, image_only = LLM only
    pdf_quality: str | None


class LlmExtractionExtractionReviewItem(pydantic.BaseModel):
    review_item_id: uuid.UUID
    run_id: uuid.UUID
    document_type: str
    source_table: str
    source_id: str
    unit_id: str | None
    legal_path: str | None
    page_start: int | None
    page_end: int | None
    severity: str
    category: str
    review_status: str
    finding: Any
    resolution: Any | None
    created_at: datetime.datetime
    updated_at: datetime.datetime


class LlmExtractionExtractionRun(pydantic.BaseModel):
    run_id: uuid.UUID
    document_type: str
    source_table: str
    source_id: str
    final_extraction_table: str | None
    final_extraction_id: uuid.UUID | None
    pdf_sha256: str
    pdf_byte_size: int | None
    page_count: int | None
    storage_path: str | None
    quality_class: str
    intake_status: str
    workflow_version: str
    schema_version: str
    run_status: str
    error_code: str | None
    error_message: str | None
    started_at: datetime.datetime | None
    completed_at: datetime.datetime | None
    created_at: datetime.datetime
    updated_at: datetime.datetime


class LlmExtractionExtractionStageArtifact(pydantic.BaseModel):
    artifact_id: uuid.UUID
    run_id: uuid.UUID
    document_type: str
    source_table: str
    source_id: str
    pdf_sha256: str
    stage_name: str
    stage_status: str
    stage_version: str
    schema_version: str
    prompt_version: str
    model_name: str
    attempt_number: int
    artifact_hash: str
    artifact_summary: Any
    artifact_payload: Any | None
    created_at: datetime.datetime


class LlmExtractionMahkamahAgungPutusan(pydantic.BaseModel):
    id: uuid.UUID
    extraction_id: str
    extraction_result: Any | None
    summary_id: str | None
    summary_en: str | None
    extraction_confidence: float | None
    content_embedding: Any | None
    summary_embedding_id: Any | None
    summary_embedding_en: Any | None
    embedding_generated: bool
    status: str
    error_message: str | None
    created_at: datetime.datetime
    updated_at: datetime.datetime


class LlmExtractionParserFeedback(pydantic.BaseModel):
    """Extraction feedback for self-improving parser loop — aggregated into GitHub Issues daily"""

    id: uuid.UUID
    source_id: int
    # reconciliation_diff, validation_warning, escalation, coverage_low
    feedback_type: str
    # Dotted field path, e.g. batang_tubuh[3].rincian_isi[0].huruf
    field_path: str | None
    details: Any
    # Git SHA or extraction_version tag at time of feedback
    parser_version: str | None
    created_at: datetime.datetime
