"""
SQLC-generated Python queries for council operations.

This package is AUTO-GENERATED by sqlc from:
- Schema: db/schemas/council_v1.sql, db/schemas/llm_extraction.sql
- Queries: internal/db/queries/council.sql, internal/db/queries/llm_extractions.sql

DO NOT EDIT - regenerate with: make sqlc-generate

Usage:
    from src.council.db.sqlc import CouncilQuerier, ExtractionQuerier
    from sqlalchemy.ext.asyncio import AsyncConnection

    council_querier = CouncilQuerier(conn)
    extraction_querier = ExtractionQuerier(conn)
"""

from .council import AsyncQuerier as CouncilQuerier
from .council import (
    CouncilV1DeliberationMessage,
    CouncilV1DeliberationSession,
    CreateCouncilMessageParams,
    CreateCouncilSessionParams,
    GetSessionsWithMessageCountsRow,
    UpdateCouncilSessionParams,
)
from .extraction import AsyncQuerier as ExtractionQuerier
from .extraction import (
    FindSimilarCasesByEmbeddingRow,
    FindSimilarCasesByEmbeddingWithFilterRow,
    GetAllCasesRow,
    GetCasesByTypePatternRow,
    GetCaseTypeDistributionRow,
    GetLLMExtractionByIDRow,
    GetSentenceStatsByCategoryRow,
    GetVerdictDistributionRow,
    TextSearchCasesRow,
)

__all__ = [
    # Council querier
    "CouncilQuerier",
    "CreateCouncilMessageParams",
    "CreateCouncilSessionParams",
    "GetSessionsWithMessageCountsRow",
    "UpdateCouncilSessionParams",
    "CouncilV1DeliberationMessage",
    "CouncilV1DeliberationSession",
    # Extraction querier
    "ExtractionQuerier",
    "FindSimilarCasesByEmbeddingRow",
    "FindSimilarCasesByEmbeddingWithFilterRow",
    "GetAllCasesRow",
    "GetCasesByTypePatternRow",
    "GetCaseTypeDistributionRow",
    "GetLLMExtractionByIDRow",
    "GetSentenceStatsByCategoryRow",
    "GetVerdictDistributionRow",
    "TextSearchCasesRow",
]
