// gen-i18n-keys reads the Indonesian TOML locale file (source of truth),
// validates key parity with the English file, and generates typed Go constants
// in internal/i18n/keys_gen.go.
//
// Usage: go run ./cmd/gen-i18n-keys
package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"unicode"

	"github.com/BurntSushi/toml"
)

const (
	idFile     = "internal/i18n/locales/id.toml"
	enFile     = "internal/i18n/locales/en.toml"
	outputFile = "internal/i18n/keys_gen.go"
)

// message mirrors the go-i18n v2 TOML structure (only the fields we need).
type message struct {
	Other string `toml:"other"`
}

func main() {
	idKeys, err := loadKeys(idFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error loading %s: %v\n", idFile, err)
		os.Exit(1)
	}

	enKeys, err := loadKeys(enFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error loading %s: %v\n", enFile, err)
		os.Exit(1)
	}

	// Validate key parity.
	if err := validateParity(idKeys, enKeys); err != nil {
		fmt.Fprintf(os.Stderr, "Key parity validation failed:\n%s\n", err)
		os.Exit(1)
	}

	// Sort keys for deterministic output.
	keys := make([]string, 0, len(idKeys))
	for k := range idKeys {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	// Generate Go source.
	if err := generateFile(keys, outputFile); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing %s: %v\n", outputFile, err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s with %d keys\n", outputFile, len(keys))
}

func loadKeys(path string) (map[string]message, error) {
	var data map[string]message
	if _, err := toml.DecodeFile(path, &data); err != nil {
		return nil, err
	}
	return data, nil
}

func validateParity(idKeys, enKeys map[string]message) error {
	var errs []string

	for k := range idKeys {
		if _, ok := enKeys[k]; !ok {
			errs = append(errs, fmt.Sprintf("  key %q exists in %s but not in %s", k, idFile, enFile))
		}
	}
	for k := range enKeys {
		if _, ok := idKeys[k]; !ok {
			errs = append(errs, fmt.Sprintf("  key %q exists in %s but not in %s", k, enFile, idFile))
		}
	}

	if len(errs) > 0 {
		sort.Strings(errs)
		return fmt.Errorf("%s", strings.Join(errs, "\n"))
	}
	return nil
}

func generateFile(keys []string, path string) error {
	var b strings.Builder
	b.WriteString("// Code generated by gen-i18n-keys. DO NOT EDIT.\n")
	b.WriteString("package i18n\n\n")
	b.WriteString("const (\n")

	for _, key := range keys {
		constName := toConstName(key)
		fmt.Fprintf(&b, "\tMsg%s = %q\n", constName, key)
	}

	b.WriteString(")\n")

	return os.WriteFile(path, []byte(b.String()), 0644)
}

// toConstName converts a TOML key like "error_invalid_page" to "ErrorInvalidPage".
func toConstName(key string) string {
	var b strings.Builder
	upper := true
	for _, r := range key {
		if r == '_' {
			upper = true
			continue
		}
		if upper {
			b.WriteRune(unicode.ToUpper(r))
			upper = false
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}
