# generated by datamodel-codegen:
#   filename:  openapi.yaml

from datetime import date as date_aliased
from enum import IntEnum, StrEnum
from typing import Annotated, Any, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, Field


class IzinUsahaItem(BaseModel):
    """
    Business license requirement
    """

    jenis_izin: Annotated[str | None, Field(description="License type")] = None
    bidang_usaha: Annotated[str | None, Field(description="Business sector")] = None


class AMLMatch(BaseModel):
    id: Annotated[
        str | None,
        Field(
            description="Source record identifier. bo_v1.cases: ULID (26 chars). interpol_red_notices: entity_id (INTERPOL notice ID).\n"
        ),
    ] = None
    name: Annotated[
        str | None,
        Field(
            description='Matched entity name. bo_v1.cases: subject field. interpol_red_notices: "family_name, forename" concatenation.\n'
        ),
    ] = None
    match_score: Annotated[
        float | None,
        Field(
            description="Trigram similarity score (>= 0.5 display threshold)",
            ge=0.5,
            le=1.0,
        ),
    ] = None


class EntityType(StrEnum):
    """
    Type of entity being screened
    """

    INDIVIDUAL = "individual"
    COMPANY = "company"


class AMLScreeningRequest(BaseModel):
    name: Annotated[
        str,
        Field(
            description="Name of individual or company to screen",
            max_length=200,
            min_length=2,
        ),
    ]
    entity_type: Annotated[
        EntityType, Field(description="Type of entity being screened")
    ]


class ScreenedType(StrEnum):
    INDIVIDUAL = "individual"
    COMPANY = "company"


class Status(StrEnum):
    """
    flagged = at least one match with score >= 0.5 found, clear = no matches in all healthy sources, incomplete = no matches but one or more sources failed (cannot guarantee clear)

    """

    FLAGGED = "flagged"
    CLEAR = "clear"
    INCOMPLETE = "incomplete"


class Source(StrEnum):
    """
    v1 sources only. v2 will add mahkamah_agung, lkpp_blacklist, sprm_offenders, and singapore_judgments as backward-compatible additions.

    """

    BENEFICIAL_OWNERSHIP = "beneficial_ownership"
    INTERPOL_RED_NOTICES = "interpol_red_notices"


class Health(StrEnum):
    """
    ok = queried successfully, error = query failed, skipped = not relevant for entity type (e.g., INTERPOL skipped for companies)

    """

    OK = "ok"
    ERROR = "error"
    SKIPPED = "skipped"


class AMLSourceResult(BaseModel):
    source: Annotated[
        Source | None,
        Field(
            description="v1 sources only. v2 will add mahkamah_agung, lkpp_blacklist, sprm_offenders, and singapore_judgments as backward-compatible additions.\n"
        ),
    ] = None
    health: Annotated[
        Health | None,
        Field(
            description="ok = queried successfully, error = query failed, skipped = not relevant for entity type (e.g., INTERPOL skipped for companies)\n"
        ),
    ] = None
    match_count: int | None = None
    matches: list[AMLMatch] | None = None


class ActorType(StrEnum):
    """
    Type of actor
    """

    PERSON = "person"
    COMPANY = "company"
    ORGANIZATION = "organization"
    PUBLIC_BODY = "public_body"


class Role(StrEnum):
    """
    Actor's relationship to the regulation
    """

    ISSUER = "issuer"
    ENFORCER = "enforcer"


class AMLActorRegulationExport(BaseModel):
    """
    Regulation linked to an actor with denormalized regulation details
    """

    role: Annotated[Role, Field(description="Actor's relationship to the regulation")]
    regulation_id: Annotated[UUID, Field(description="UUID of the regulation")]
    canonical_title: Annotated[
        str, Field(description="Full official title of the regulation")
    ]
    form: Annotated[
        str | None,
        Field(
            description="Regulation form (undang-undang, peraturan_pemerintah, etc.)"
        ),
    ] = None
    number: Annotated[str | None, Field(description="Regulation number")] = None
    year: Annotated[str | None, Field(description="Regulation year")] = None
    jurisdiction: Annotated[str, Field(description="Jurisdiction code (ID, SG, MY)")]
    status: Annotated[
        str | None,
        Field(
            description="Regulation status (berlaku, tidak_berlaku, dicabut, diubah, current, repealed, revised)"
        ),
    ] = None


class EventType(StrEnum):
    """
    Type of AML event
    """

    VERDICT = "verdict"
    SANCTION = "sanction"
    BLACKLIST_ENTRY = "blacklist_entry"


class AMLIdentifierExport(BaseModel):
    """
    External registry identifier for an actor
    """

    scheme: Annotated[
        str,
        Field(
            description="Identifier scheme (passport, npwp, lkpp_id, lei, nib, siup, etc.)"
        ),
    ]
    identifier: Annotated[str, Field(description="Identifier value")]


class Direction(StrEnum):
    """
    Direction relative to the actor (outgoing = actor is source, incoming = actor is target)
    """

    OUTGOING = "outgoing"
    INCOMING = "incoming"


class AMLLinkExport(BaseModel):
    """
    Actor-to-actor relationship
    """

    link_type: Annotated[
        str,
        Field(
            description="Relationship type (ownership, directorship, employment, family, associate)"
        ),
    ]
    direction: Annotated[
        Direction,
        Field(
            description="Direction relative to the actor (outgoing = actor is source, incoming = actor is target)"
        ),
    ]
    related_actor_id: Annotated[UUID, Field(description="UUID of the related actor")]
    related_actor_name: Annotated[
        str, Field(description="Canonical name of the related actor")
    ]
    is_current: Annotated[
        bool, Field(description="Whether this relationship is currently active")
    ]
    properties: Annotated[
        dict[str, Any] | None,
        Field(description="Link-specific attributes (e.g., share_pct, role)"),
    ] = None


class AMLNameExport(BaseModel):
    """
    Name variant for an actor
    """

    name: Annotated[str, Field(description="Name value")]
    is_primary: Annotated[
        bool, Field(description="Whether this is the canonical/primary name")
    ]


class Role1(StrEnum):
    """
    How the regulation relates to the event
    """

    LEGAL_BASIS = "legal_basis"
    PROVEN_ARTICLE = "proven_article"
    CITED = "cited"


class AMLEventRegulationExport(BaseModel):
    """
    Regulation linked to an event with denormalized regulation details
    """

    role: Annotated[Role1, Field(description="How the regulation relates to the event")]
    article: Annotated[
        str | None,
        Field(description='Specific article/pasal reference (e.g., "Pasal 378")'),
    ] = None
    regulation_id: Annotated[UUID, Field(description="UUID of the regulation")]
    canonical_title: Annotated[
        str, Field(description="Full official title of the regulation")
    ]
    form: Annotated[
        str | None,
        Field(
            description="Regulation form (undang-undang, peraturan_pemerintah, etc.)"
        ),
    ] = None
    number: Annotated[str | None, Field(description="Regulation number")] = None
    year: Annotated[str | None, Field(description="Regulation year")] = None
    jurisdiction: Annotated[str, Field(description="Jurisdiction code (ID, SG, MY)")]
    status: Annotated[
        str | None,
        Field(
            description="Regulation status (berlaku, tidak_berlaku, dicabut, diubah, current, repealed, revised)"
        ),
    ] = None


class AgentId(StrEnum):
    """
    Identifiers for the judicial AI agents
    """

    STRICT = "strict"
    HUMANIST = "humanist"
    HISTORIAN = "historian"


class PositionStance(StrEnum):
    """
    An agent's stance on a deliberation issue
    """

    AGREE = "agree"
    DISAGREE = "disagree"
    PARTIAL = "partial"
    NO_POSITION = "no_position"


class Type(StrEnum):
    AGENT = "agent"


class AgentSender(BaseModel):
    type: Literal["agent"]
    agent_id: AgentId


class AnalyticsDistributionItem(BaseModel):
    label: Annotated[
        str, Field(description="Category label (translated based on Accept-Language)")
    ]
    count: Annotated[int, Field(description="Number of cases in this category")]
    percentage: Annotated[float, Field(description="Percentage of total cases (0-100)")]


class AnalyticsOverview(BaseModel):
    total_cases: int
    total_guilty_verdict: int
    total_state_loss: float


class AnalyticsSummary(BaseModel):
    total_cases: Annotated[int, Field(description="Total number of validated cases")]
    distinct_countries: Annotated[int, Field(description="Number of unique countries")]
    latest_year: Annotated[str, Field(description="Most recent case year")]


class ApplicableLaw(BaseModel):
    """
    An applicable law reference
    """

    law_reference: Annotated[
        str, Field(description="Reference to the law (e.g., Article 2 UU 31/1999)")
    ]
    description: Annotated[str, Field(description="Description of the law")]
    how_it_applies: Annotated[
        str, Field(description="How this law applies to the case")
    ]


class ArgumentPoint(BaseModel):
    """
    A single argument point in the legal opinion
    """

    argument: Annotated[
        str,
        Field(
            description='Single bullet-point legal argument. ONE concise sentence stating\nonly the substantive legal point — no greetings, honorifics\n("Yang Mulia"), speaker self-references ("Saya berpendapat"), or\nintroductory framing. Suitable for direct rendering as a list\nitem. Maximum ~40 words.\n',
            examples=[
                "Terdakwa terbukti merugikan keuangan negara sebesar Rp 5 miliar, memenuhi unsur Pasal 2 UU Tipikor."
            ],
            max_length=400,
        ),
    ]
    source_agent: AgentId
    supporting_cases: Annotated[
        list[str] | None, Field(description="Cases supporting this argument")
    ] = None
    strength: Annotated[
        str, Field(description="Argument strength (strong, moderate, weak)")
    ]


class BeneficialOwnershipAnalytics(BaseModel):
    summary: AnalyticsSummary
    cases_per_year: list[AnalyticsDistributionItem]
    cases_per_country: list[AnalyticsDistributionItem]
    cases_per_subject_type: list[AnalyticsDistributionItem]
    cases_per_case_type: list[AnalyticsDistributionItem]


class FieldMeta(BaseModel):
    schema_version: Annotated[
        str, Field(description='Schema version for backward compatibility (e.g., "2")')
    ]
    count: Annotated[int, Field(description="Number of records in this batch")]
    has_more: Annotated[bool, Field(description="Whether more records are available")]
    cursor: Annotated[
        str | None,
        Field(
            description='Cursor for fetching the next batch (format "updated_at|id")'
        ),
    ] = None


class BulkExportMeta(BaseModel):
    """
    Metadata line (always the last line in NDJSON stream)
    """

    field_meta: Annotated[FieldMeta, Field(alias="_meta")]


class BlacklistDefaults(BaseModel):
    subject_type: str
    case_type: str
    country: str
    year_start: int
    year_end: int


class FilterOption(BaseModel):
    value: str
    label: str
    count: Annotated[
        int | None, Field(description="Optional - number of records with this value")
    ] = None


class YearRange(BaseModel):
    min: int
    max: int


class CaseType(StrEnum):
    VERDICT = "verdict"
    BLACKLIST = "blacklist"
    SANCTION = "sanction"


class BlacklistMatch(BaseModel):
    company_name: str | None = None
    source: Annotated[
        str | None,
        Field(
            description="Where the company was found (peserta, pemenang, pemenang_berkontrak)"
        ),
    ] = None
    case_id: str | None = None
    case_subject: str | None = None
    case_type: CaseType | None = None
    match_score: Annotated[
        float | None, Field(description="Fuzzy match similarity score (0-1)")
    ] = None
    decision_number: str | None = None
    case_date: AwareDatetime | None = None
    punishment_end: AwareDatetime | None = None


class BudgetByType(BaseModel):
    label: str | None = None
    count: int | None = None
    total_budget: str | None = None


class BudgetByYear(BaseModel):
    year: str | None = None
    tender_count: int | None = None
    total_budget: str | None = None
    avg_budget: str | None = None


class BudgetEfficiency(BaseModel):
    efficiency_level: Annotated[
        str | None,
        Field(
            description="Efficiency level (missing_data, exact_match, under_90_pct, efficient, over_budget)"
        ),
    ] = None
    count: int | None = None
    avg_pagu: str | None = None
    avg_hps: str | None = None


class Status1(StrEnum):
    DELETED = "deleted"
    VALIDATED = "validated"
    DRAFT = "draft"


class CaseDetail(BaseModel):
    id: str
    subject: str
    subject_type: Annotated[
        str, Field(description="Subject type (translated based on Accept-Language)")
    ]
    person_in_charge: str | None = None
    beneficial_ownership: str | None = None
    date: AwareDatetime | None = None
    decision_number: str | None = None
    source: str
    link: str
    nation: str
    punishment_duration: Annotated[
        str | None, Field(description="Formatted date range")
    ] = None
    type: Annotated[
        str, Field(description="Case type (translated based on Accept-Language)")
    ]
    year: str
    summary: str
    status: Status1
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class InputType(StrEnum):
    """
    Type of case input
    """

    TEXT_SUMMARY = "text_summary"
    EXTRACTION_ID = "extraction_id"


class CorruptionDetails(BaseModel):
    """
    Details specific to corruption cases
    """

    state_loss_idr: float
    position: str | None = None


class CouncilCaseType(StrEnum):
    """
    Types of legal cases
    """

    NARCOTICS = "narcotics"
    CORRUPTION = "corruption"
    GENERAL_CRIMINAL = "general_criminal"
    OTHER = "other"


class CouncilDefendantProfile(BaseModel):
    """
    Profile of the defendant in a case
    """

    is_first_offender: bool | None = True
    age: int | None = None
    occupation: str | None = None


class NarcoticsIntent(StrEnum):
    """
    Intent classification for narcotics cases
    """

    PERSONAL_USE = "personal_use"
    DISTRIBUTION = "distribution"
    UNKNOWN = "unknown"


class CaseOverview(BaseModel):
    id: str
    court_location: str | None = None
    verdict_date: date_aliased | None = None
    defendant_name: str | None = None
    verdict_number: str | None = None
    court_name: str | None = None
    law_name: str | None = None
    court_level: str | None = None


class CaseRecord(BaseModel):
    """
    A case record from the database
    """

    id: str | None = None
    case_number: str | None = None
    case_type: CouncilCaseType | None = None
    court_name: str | None = None
    court_type: str | None = None
    decision_date: str | None = None
    defendant_name: str | None = None
    defendant_age: int | None = None
    defendant_first_offender: bool | None = None
    indictment: dict[str, Any] | None = None
    narcotics_details: dict[str, Any] | None = None
    corruption_details: dict[str, Any] | None = None
    legal_facts: dict[str, Any] | None = None
    verdict: dict[str, Any] | None = None
    legal_basis: list[str] | None = None
    is_landmark_case: bool | None = False
    extraction_result: dict[str, Any] | None = None
    summary_en: str | None = None
    summary_id: str | None = None


class CaseStatisticsResponse(BaseModel):
    """
    Response for case statistics
    """

    total_cases: int
    sentence_distribution: dict[str, Any]
    verdict_distribution: dict[str, Any]


class DetentionEvent(BaseModel):
    date: str | None = None
    location: str | None = None
    status: str | None = None
    description: str | None = None


class CasesTrendItem(BaseModel):
    year: int
    count: int


class ChartItem(BaseModel):
    label: str
    value: float


class ChatbotReferenceRequest(BaseModel):
    case_numbers: list[str]


class Datum(BaseModel):
    case_number: str | None = None
    url: str | None = None


class ChatbotReferenceResponse(BaseModel):
    data: list[Datum]


class ChatbotRequest(BaseModel):
    thread_id: str
    user_message: Annotated[str, Field(max_length=5000)]


class Reference(Datum):
    pass


class ChatbotResponse(BaseModel):
    response: str
    references: list[Reference] | None = None


class CitedPrecedent(BaseModel):
    """
    A precedent case cited in the opinion
    """

    case_id: Annotated[
        str, Field(description="Unique identifier of the precedent case")
    ]
    case_number: Annotated[str, Field(description="Official case number")]
    relevance: Annotated[str, Field(description="Why this case is relevant")]
    verdict_summary: Annotated[str, Field(description="Summary of the verdict")]
    how_it_applies: Annotated[
        str, Field(description="How this precedent applies to the current case")
    ]


class CompetitionHealth(BaseModel):
    level: Annotated[
        str | None,
        Field(
            description="Competition level (no_bidders, single_bidder, low, medium, high)"
        ),
    ] = None
    tender_count: int | None = None
    avg_budget: str | None = None


class CompetitionMetrics(BaseModel):
    total_tenders: int | None = None
    avg_participants: float | None = None
    low_competition_count: int | None = None
    no_winner_count: int | None = None


class ContinueDiscussionRequest(BaseModel):
    num_rounds: Annotated[
        int | None,
        Field(
            description="Number of discussion rounds (each round = all judges respond)",
            ge=1,
            le=3,
        ),
    ] = 1


class Type1(StrEnum):
    SYSTEM = "system"


class SystemSender(BaseModel):
    type: Literal["system"]


class Type2(StrEnum):
    USER = "user"


class UserSender(BaseModel):
    type: Literal["user"]


class CouncilSimilarCase(BaseModel):
    """
    A similar case found via semantic search
    """

    case_id: str
    case_number: str
    similarity_score: float
    similarity_reason: str
    verdict_summary: str
    sentence_months: int


class StructuredCaseData(BaseModel):
    """
    Optional structured data that can be provided with case input
    """

    case_type: CouncilCaseType | None = None
    defendant_age: int | None = None
    defendant_first_offender: bool | None = None
    substance_type: str | None = None
    weight_grams: float | None = None
    state_loss_idr: float | None = None


class CreateSessionStreamEventType(StrEnum):
    """
    Event types emitted while creating a deliberation session
    """

    STATUS = "status"
    SESSION_CREATED = "session_created"
    AGENT_START = "agent_start"
    CHUNK = "chunk"
    AGENT_COMPLETE = "agent_complete"
    SESSION_COMPLETE = "session_complete"
    ERROR = "error"


class TopOccupation(BaseModel):
    occupation: str
    count: int


class DefendantProfile(BaseModel):
    id: str
    defendant_name: str | None = None
    defendant_age: int | None = None
    defendant_gender: str | None = None
    defendant_occupation: str | None = None
    defendant_education: str | None = None
    defendant_location: str | None = None


class DeliberationPhase(StrEnum):
    """
    Current phase of a deliberation session
    """

    LEGACY = "legacy"
    OPENING = "opening"
    DEBATE = "debate"
    CONVERGENCE = "convergence"
    SUMMARY = "summary"


class PhaseHistoryItem(BaseModel):
    phase: str | None = None
    entered_at: AwareDatetime | None = None
    round: int | None = None


class SessionStatus(StrEnum):
    """
    Status of a deliberation session
    """

    ACTIVE = "active"
    CONCLUDED = "concluded"
    ARCHIVED = "archived"


class Error(BaseModel):
    error: str
    status_code: int | None = None


class FeaturedCase(BaseModel):
    id: str
    defendant_name: str | None = None
    law_name: str | None = None
    court_name: str | None = None
    verdict_result: str | None = None
    imprisonment_duration_months: int | None = None
    state_loss_proven: float | None = None
    amount_returned: float | None = None
    verdict_date: date_aliased | None = None


class FinancialAnalysis(BaseModel):
    id: str
    state_loss: float | None = None
    amount_returned: float | None = None
    fine_imposed: float | None = None
    subsidiary_duration_months: int | None = None


class FinancialOverview(BaseModel):
    total_state_loss: float
    total_recovered: float
    total_fines: float


class GenerateOpinionRequest(BaseModel):
    """
    Request to generate a legal opinion
    """

    include_dissent: bool | None = True


class LegalArguments(BaseModel):
    """
    Collected legal arguments from the deliberation
    """

    for_conviction: Annotated[
        list[ArgumentPoint] | None, Field(description="Arguments supporting conviction")
    ] = None
    for_leniency: Annotated[
        list[ArgumentPoint] | None, Field(description="Arguments supporting leniency")
    ] = None
    for_severity: Annotated[
        list[ArgumentPoint] | None, Field(description="Arguments supporting severity")
    ] = None


class SentenceRange(BaseModel):
    """
    A range for sentencing recommendations
    """

    minimum: Annotated[int, Field(description="Minimum sentence value")]
    maximum: Annotated[int, Field(description="Maximum sentence value")]
    recommended: Annotated[int, Field(description="Recommended sentence value")]


class VerdictDecision(StrEnum):
    """
    Possible verdict decisions
    """

    GUILTY = "guilty"
    NOT_GUILTY = "not_guilty"
    ACQUITTED = "acquitted"


class GetCaseResponse(BaseModel):
    """
    Response for getting a single case
    """

    case: CaseRecord


class GraphFiltersResponse(BaseModel):
    institutions: Annotated[
        list[FilterOption], Field(description="Available institutions for filtering")
    ]
    datasets: Annotated[
        list[FilterOption],
        Field(description="Available dataset categories (all, procurement, aml)"),
    ]


class GraphLink(BaseModel):
    source: Annotated[UUID, Field(description="Source actor UUID")]
    target: Annotated[UUID, Field(description="Target actor UUID")]
    type: Annotated[
        str,
        Field(description="Link type (ownership, directorship, buyer_winner, etc.)"),
    ]
    label: Annotated[str, Field(description="Human-readable label for the link")]
    dataset: Annotated[str, Field(description="Dataset source of this link")]


class Type3(StrEnum):
    """
    Actor type from entity_graph
    """

    PERSON = "person"
    COMPANY = "company"
    ORGANIZATION = "organization"
    PUBLIC_BODY = "public_body"


class GraphNode(BaseModel):
    id: Annotated[UUID, Field(description="Actor UUID from entity_graph")]
    label: Annotated[str, Field(description="Primary name of the actor")]
    type: Annotated[Type3, Field(description="Actor type from entity_graph")]
    risk_score: Annotated[
        int,
        Field(
            description="Count of AML events (verdicts + blacklist entries + sanctions)"
        ),
    ]
    datasets: Annotated[
        list[str], Field(description="Dataset sources this actor appears in")
    ]
    event_counts: Annotated[
        dict[str, int],
        Field(
            description="Event counts keyed by event_type (tender, verdict, sanction, blacklist_entry)"
        ),
    ]


class GraphResponse(BaseModel):
    nodes: list[GraphNode]
    links: list[GraphLink]
    truncated: Annotated[
        bool,
        Field(
            description="True if results were capped (e.g., expand exceeded 100 neighbors)"
        ),
    ]


class GroupName(StrEnum):
    KEMENTERIAN = "Kementerian"
    BADAN_USAHA_MILIK_NEGARA = "Badan Usaha Milik Negara"
    LEMBAGA_PEMERINTAH_NONKEMENTERIAN = "Lembaga Pemerintah Nonkementerian"
    PEMERINTAH_DAERAH = "Pemerintah Daerah"


class InstansiGroup(BaseModel):
    group_name: GroupName
    institutions: list[FilterOption]


class KBKIItem(BaseModel):
    """
    KBKI classification entry
    """

    divisi: str | None = None
    kelompok: str | None = None
    deskripsi: str | None = None
    tahun: str | None = None


class KeyViolation(BaseModel):
    id: str
    violations: list[str]


class LKPPChartData(BaseModel):
    blacklist_by_province: list[ChartItem]
    ceiling: list[ChartItem]
    top_reporters: list[ChartItem]
    scenario: list[ChartItem]
    violation: list[ChartItem]


class Country(StrEnum):
    INDONESIA = "Indonesia"
    MALAYSIA = "Malaysia"
    SINGAPORE = "Singapore"


class LatestSanctionItem(BaseModel):
    id: Annotated[
        str,
        Field(
            description="ULID identifier, resolves via /v1/beneficial-ownership/detail/{id}"
        ),
    ]
    country: Country
    source: Annotated[
        str,
        Field(
            description="Data source name (e.g. LKPP, SPRM, Singapore Supreme Court)"
        ),
    ]
    name: Annotated[str, Field(description="Subject name")]
    case_type: Annotated[
        str,
        Field(
            description="Case type (translated based on Accept-Language header):\n- en: verdict, blacklist, sanction\n- id: putusan, daftar hitam, sanksi"
        ),
    ]
    date: Annotated[date_aliased | None, Field(description="Case date")] = None


class LatestSanctionsResponse(BaseModel):
    data: list[LatestSanctionItem]


class LatestTenderItem(BaseModel):
    id: int
    kode_tender: str
    nama_tender: str
    instansi: str | None = None
    tahun_anggaran: str | None = None
    nilai_pagu: str | None = None
    tahap_saat_ini: str | None = None


class LatestTendersResponse(BaseModel):
    budget_year: Annotated[int, Field(description="The latest budget year")]
    data: Annotated[list[LatestTenderItem], Field(max_length=3)]


class MessageIntent(StrEnum):
    """
    Intent classification for user messages
    """

    ASK_OPINION = "ask_opinion"
    REQUEST_COMPARISON = "request_comparison"
    CHALLENGE_VIEW = "challenge_view"
    SEEK_CONSENSUS = "seek_consensus"
    GENERAL_QUESTION = "general_question"
    ADDRESS_AGENT = "address_agent"
    INTRODUCE_EVIDENCE = "introduce_evidence"
    REQUEST_SUMMARY = "request_summary"
    OVERRIDE_SUGGESTION = "override_suggestion"


class MethodAnalysis(BaseModel):
    method: str | None = None
    tender_count: int | None = None
    total_budget: str | None = None
    avg_participants: float | None = None
    avg_budget: str | None = None


class MonthlyTrend(BaseModel):
    month: Annotated[str | None, Field(description="Month in YYYY-MM format")] = None
    tender_count: int | None = None
    total_budget: str | None = None
    avg_participants: float | None = None


class PaginationMeta(BaseModel):
    current_page: int
    last_page: int
    per_page: int
    total: int


class PipelineStatus(BaseModel):
    status: Annotated[
        str | None,
        Field(
            description="Status category (completed, cancelled, disputed, awarded, evaluation, in_progress)"
        ),
    ] = None
    count: int | None = None
    total_budget: str | None = None


class RiskIndicators(BaseModel):
    total_tenders: int | None = None
    single_bidder_count: int | None = None
    cancelled_count: int | None = None
    over_hps_count: int | None = None
    no_bidder_count: int | None = None
    single_bidder_pct: float | None = None
    cancellation_rate: float | None = None


class TopWinner(BaseModel):
    company_name: str | None = None
    win_count: int | None = None
    total_contract_value: str | None = None
    is_blacklisted: bool | None = None


class WinnerConcentration(BaseModel):
    company_name: str | None = None
    wins: int | None = None
    total_value: str | None = None
    market_share_pct: float | None = None


class TenderHasilEvaluasi(BaseModel):
    """
    Evaluation result for a participant
    """

    npwp: Annotated[str | None, Field(description="Tax identification number")] = None
    nama_peserta: Annotated[
        str | None, Field(description="Participant company name")
    ] = None
    harga_penawaran: Annotated[str | None, Field(description="Bid price offered")] = (
        None
    )
    hasil_negosiasi: Annotated[str | None, Field(description="Negotiation result")] = (
        None
    )
    status_evaluasi: Annotated[
        str | None, Field(description="Evaluation status/result")
    ] = None
    harga_terkoreksi: Annotated[str | None, Field(description="Corrected price")] = None


class TenderPemenang(BaseModel):
    """
    Tender winner information
    """

    npwp: Annotated[
        str | None, Field(description="Tax identification number (partially masked)")
    ] = None
    alamat: Annotated[str | None, Field(description="Company address")] = None
    nama_pemenang: Annotated[str | None, Field(description="Winner company name")] = (
        None
    )
    harga_penawaran: Annotated[str | None, Field(description="Bid price offered")] = (
        None
    )
    hasil_negosiasi: Annotated[str | None, Field(description="Negotiation result")] = (
        None
    )
    harga_terkoreksi: Annotated[
        str | None, Field(description="Corrected/final price")
    ] = None


class TenderPeserta(BaseModel):
    """
    Tender participant information
    """

    nama_peserta: Annotated[
        str | None, Field(description="Participant company name")
    ] = None
    harga_penawaran: Annotated[str | None, Field(description="Bid price offered")] = (
        None
    )
    harga_terkoreksi: Annotated[
        str | None, Field(description="Corrected price after evaluation")
    ] = None


class RealisasiEntry(BaseModel):
    """
    Contract realization milestone entry
    """

    no: Annotated[str | None, Field(description="Entry sequence number")] = None
    jenis_realisasi: Annotated[
        str | None, Field(description="Realization type (e.g., Termin 1)")
    ] = None
    nilai_realisasi: Annotated[str | None, Field(description="Payment amount")] = None
    tanggal_realisasi: Annotated[str | None, Field(description="Payment date")] = None


class TenderJadwalHistory(BaseModel):
    """
    Schedule change history entry
    """

    no: str | None = None
    tanggal_edit: Annotated[str | None, Field(description="Edit date")] = None
    original_mulai: Annotated[str | None, Field(description="Original start date")] = (
        None
    )
    original_sampai: Annotated[str | None, Field(description="Original end date")] = (
        None
    )
    keterangan: Annotated[str | None, Field(description="Change notes")] = None


class ProcurementListItem(BaseModel):
    kode_tender: str
    nama_tender: str
    instansi: str | None = None
    nilai_pagu: str | None = None
    tahun_anggaran: str | None = None
    tahap_saat_ini: str | None = None
    tanggal_pembuatan: date_aliased | None = None
    peserta_count: int | None = None
    search_score: Annotated[
        float | None,
        Field(description="BM25 relevance score (only present when searching)"),
    ] = None


class ProcurementListResponse(BaseModel):
    data: list[ProcurementListItem]
    meta: PaginationMeta


class ProvenArticle(BaseModel):
    law_name: str | None = None
    article: str | None = None
    description: str | None = None


class SPSEDistributionItem(BaseModel):
    label: Annotated[str, Field(description="Category label")]
    count: Annotated[int, Field(description="Number of items in this category")]
    percentage: Annotated[float, Field(description="Percentage of total")]
    total_value: Annotated[
        float | None, Field(description="Total value (Pagu) for this category")
    ] = None


class RiskLevel(StrEnum):
    """
    Competition risk level
    """

    LOW = "low"
    MODERATE = "moderate"
    HIGH = "high"
    UNKNOWN = "unknown"


class SPSECompetitionMetrics(BaseModel):
    avg_bidders_per_tender: Annotated[
        float, Field(description="Average number of bidders per tender")
    ]
    single_bidder_rate: Annotated[
        float, Field(description="Percentage of tenders with only one bidder")
    ]
    tenders_analyzed: Annotated[int, Field(description="Number of tenders analyzed")]
    risk_level: Annotated[
        RiskLevel | None, Field(description="Competition risk level")
    ] = None


class Lang(StrEnum):
    """
    Response language
    """

    ID = "id"
    EN = "en"


class SPSEDashboardSummary(BaseModel):
    total_tenders: Annotated[int, Field(description="Total number of tenders")]
    active_tenders: Annotated[
        int,
        Field(description="Number of active tenders (not cancelled/failed/completed)"),
    ]
    institution_count: Annotated[
        int, Field(description="Number of distinct institutions")
    ]
    conclusion: Annotated[
        str, Field(description="Bilingual conclusion about the summary")
    ]


class SPSEDashboardDistributionItem(BaseModel):
    label: Annotated[
        str, Field(description="Bucket label (translated based on language)")
    ]
    count: Annotated[int, Field(description="Number of items in this bucket")]
    percentage: Annotated[float, Field(description="Percentage of total")]
    total_value: Annotated[
        float | None,
        Field(
            description="Total value for this bucket (optional, for procurement types)"
        ),
    ] = None


class SPSEInstitution(BaseModel):
    name: Annotated[str, Field(description="Institution name")]
    tender_count: Annotated[
        int, Field(description="Number of tenders from this institution")
    ]


class Type4(StrEnum):
    """
    Institution type code
    """

    BUMN = "bumn"
    KEMENTERIAN = "kementerian"
    LEMBAGA = "lembaga"
    PEMERINTAH_DAERAH = "pemerintah_daerah"


class SPSEInstitutionGroup(BaseModel):
    type: Annotated[Type4, Field(description="Institution type code")]
    label: Annotated[str, Field(description="Display label for the group")]
    institutions: list[SPSEInstitution]


class SPSEInstitutionsResponse(BaseModel):
    groups: list[SPSEInstitutionGroup]


class SPSEJenisPengadaanItem(BaseModel):
    jenis_pengadaan: Annotated[str, Field(description="Procurement type name")]
    tender_count: Annotated[int, Field(description="Number of tenders with this type")]


class SPSETopTender(BaseModel):
    kode_tender: Annotated[str, Field(description="Tender code")]
    nama_tender: Annotated[str, Field(description="Tender name")]
    instansi: Annotated[str, Field(description="Institution name")]
    satuan_kerja: Annotated[str | None, Field(description="Work unit")] = None
    jenis_pengadaan: Annotated[str | None, Field(description="Procurement type")] = None
    metode_pengadaan: Annotated[str | None, Field(description="Procurement method")] = (
        None
    )
    nilai_pagu: Annotated[float, Field(description="Budget ceiling value")]
    nilai_hps: Annotated[float | None, Field(description="Estimated price")] = None
    peserta_count: Annotated[int | None, Field(description="Number of bidders")] = None
    tanggal_pembuatan: Annotated[
        date_aliased | None, Field(description="Creation date")
    ] = None
    tahap_saat_ini: Annotated[str | None, Field(description="Current stage")] = None


class SPSEYearlyTrend(BaseModel):
    year: Annotated[int, Field(description="Year")]
    tender_count: Annotated[int, Field(description="Number of tenders")]
    total_pagu: Annotated[float, Field(description="Total budget ceiling (Nilai Pagu)")]
    total_hps: Annotated[
        float | None, Field(description="Total estimated price (Nilai HPS)")
    ] = None
    avg_peserta: Annotated[
        float | None, Field(description="Average number of bidders")
    ] = None


class EntityType1(StrEnum):
    PERSON = "person"
    ORGANIZATION = "organization"


class ScreeningEntityName(BaseModel):
    id: UUID
    name_value: str
    name_type: str
    is_matchable: bool


class ScreeningSanctionsList(BaseModel):
    id: UUID
    name: str
    publisher: str
    url: str | None = None
    description: str | None = None


class ScreeningPagination(BaseModel):
    current_page: int
    per_page: int


class ScreeningSearchItem(BaseModel):
    entity_id: UUID
    name: Annotated[str, Field(description="Best-matching name for this entity")]
    score: Annotated[float, Field(description="BM25 relevance score")]
    entity_type: EntityType1
    topics: list[str]


class QueryType(StrEnum):
    """
    Indicates query specificity. "broad" for single-word queries (higher threshold). "specific" for multi-word queries (normal threshold).
    """

    BROAD = "broad"
    SPECIFIC = "specific"


class ScreeningSearchResponse(BaseModel):
    items: list[ScreeningSearchItem]
    pagination: ScreeningPagination
    query_type: Annotated[
        QueryType,
        Field(
            description='Indicates query specificity. "broad" for single-word queries (higher threshold). "specific" for multi-word queries (normal threshold).'
        ),
    ]


class ScreeningSourcesResponse(BaseModel):
    sources: list[ScreeningSanctionsList]


class SearchCasesRequest(BaseModel):
    """
    Request for searching cases
    """

    query: str
    limit: int | None = 10
    semantic_search: bool | None = True
    filters: StructuredCaseData | None = None


class SearchCasesResponse(BaseModel):
    """
    Response for case search
    """

    cases: list[CaseRecord]
    total: int


class SearchResult(BaseModel):
    id: str
    subject: str
    subject_type: Annotated[
        str,
        Field(
            description="Subject type (translated based on Accept-Language header):\n- en: individual, company, organization\n- id: individu, perusahaan, organisasi\n"
        ),
    ]
    person_in_charge: str | None = None
    beneficial_ownership: str | None = None
    nation: str
    type: Annotated[
        str,
        Field(
            description="Case type (translated based on Accept-Language header):\n- en: verdict, blacklist, sanction\n- id: putusan, daftar hitam, sanksi\n"
        ),
    ]
    year: str


class SearchSummary(BaseModel):
    by_type: list[ChartItem] | None = None
    by_subject_type: list[ChartItem] | None = None


class TargetAgent(StrEnum):
    """
    Target a specific agent or all agents
    """

    LEGALIS = "legalis"
    HUMANIS = "humanis"
    SEJARAWAN = "sejarawan"
    STRICT = "strict"
    HUMANIST = "humanist"
    HISTORIAN = "historian"
    ALL = "all"


class SendMessageRequest(BaseModel):
    content: Annotated[
        str,
        Field(
            description="Message content to send to the council",
            max_length=5000,
            min_length=1,
        ),
    ]
    target_agent: Annotated[
        TargetAgent | None, Field(description="Target a specific agent or all agents")
    ] = None


class SenderType(StrEnum):
    """
    Type of message sender
    """

    USER = "user"
    AGENT = "agent"
    SYSTEM = "system"


class SentenceDetails(BaseModel):
    id: str
    imprisonment_duration_months: int | None = None
    proven_articles: list[ProvenArticle]


class SimilarCase(BaseModel):
    id: Annotated[
        str | None, Field(description="Case ULID", pattern="^[0-9A-HJKMNP-TV-Z]{26}$")
    ] = None
    title: Annotated[str | None, Field(description="Case title")] = None
    summary: Annotated[str | None, Field(description="Case summary")] = None
    decision: Annotated[str | None, Field(description="Court decision")] = None
    similarity_score: Annotated[
        float | None, Field(description="Semantic similarity score (0-1)")
    ] = None
    year: Annotated[int | None, Field(description="Decision year")] = None
    court: Annotated[str | None, Field(description="Court name")] = None


class StreamContinueRequest(ContinueDiscussionRequest):
    pass


class StreamEventType(StrEnum):
    """
    Types of streaming events
    """

    AGENT_START = "agent_start"
    CHUNK = "chunk"
    AGENT_COMPLETE = "agent_complete"
    AGENT_ERROR = "agent_error"
    USER_MESSAGE = "user_message"
    DELIBERATION_COMPLETE = "deliberation_complete"
    PHASE_TRANSITION = "phase_transition"
    CONVERGENCE_SUGGESTION = "convergence_suggestion"
    SUMMARY_READY = "summary_ready"


class StreamMessageRequest(BaseModel):
    content: Annotated[
        str, Field(description="Message content to send", max_length=5000, min_length=1)
    ]
    target_agent: Annotated[
        TargetAgent | None, Field(description="Target a specific agent or all agents")
    ] = None


class TenderDefaults(BaseModel):
    jenis_pengadaan: str
    instansi: str
    tahapan: str
    year_start: int
    year_end: int


class TenderFiltersResponse(BaseModel):
    jenis_pengadaan: list[FilterOption]
    instansi_groups: Annotated[
        list[InstansiGroup], Field(description="Institutions grouped by type")
    ]
    tahapan: Annotated[
        list[FilterOption], Field(description="Tender stages in chronological order")
    ]
    year_range: YearRange
    defaults: TenderDefaults


class VerdictCount(BaseModel):
    guilty: int
    not_guilty: int


class VerdictListItem(BaseModel):
    id: str
    verdict_number: str | None = None
    defendant_name: str | None = None
    court_name: str | None = None
    verdict_date: date_aliased | None = None
    verdict_result: str | None = None
    sentence_duration_months: int | None = None
    state_loss: float | None = None
    recovered: float | None = None
    fine: float | None = None


class ViolationType(BaseModel):
    violation_type: str
    count: int


class Category(StrEnum):
    DOCUMENT = "document"
    IMAGE = "image"
    TRAINING_MATERIAL = "training_material"
    OTHER = "other"


class Status2(StrEnum):
    DRAFT = "draft"
    PUBLISHED = "published"


class UploadStatus(StrEnum):
    PENDING = "pending"
    CONFIRMED = "confirmed"


class CmsFile(BaseModel):
    id: str
    filename: str
    original_filename: str
    mime_type: str
    file_size: int
    s3_key: str | None = None
    title: str | None = None
    alt_text: str | None = None
    public_url: str | None = None
    category: Category
    description: str | None = None
    status: Status2
    upload_status: UploadStatus | None = None
    published_at: AwareDatetime | None = None
    created_by: str | None = None
    updated_by: str | None = None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class CmsFileListResponse(BaseModel):
    data: list[CmsFile]
    pagination: PaginationMeta


class Success(IntEnum):
    INTEGER_0 = 0
    INTEGER_1 = 1


class File(BaseModel):
    url: str | None = None


class CmsImageUploadResponse(BaseModel):
    success: Success
    file: File | None = None


class PageType(StrEnum):
    PROFILE = "profile"
    VISION_MISSION = "vision_mission"
    ABOUT = "about"
    CONTACT = "contact"
    CUSTOM = "custom"


class CmsPage(BaseModel):
    id: str
    title: str
    title_en: str | None = None
    slug: str
    content: Annotated[
        dict[str, Any] | None, Field(description="EditorJS JSON content")
    ] = None
    content_en: Annotated[
        dict[str, Any] | None, Field(description="EditorJS JSON content (English)")
    ] = None
    page_type: PageType | None = None
    sort_order: int | None = None
    status: Status2
    published_at: AwareDatetime | None = None
    created_by: str | None = None
    updated_by: str | None = None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class CmsPageDetailResponse(BaseModel):
    data: CmsPage


class CmsPageListResponse(BaseModel):
    data: list[CmsPage]
    pagination: PaginationMeta


class CmsPost(BaseModel):
    id: str
    title: str
    title_en: str | None = None
    slug: str
    content: dict[str, Any] | None = None
    content_en: dict[str, Any] | None = None
    excerpt: str | None = None
    cover_image_url: str | None = None
    tags: list[str]
    status: Status2
    published_at: AwareDatetime | None = None
    created_by: str | None = None
    updated_by: str | None = None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class CmsPostDetailResponse(BaseModel):
    data: CmsPost


class CmsPostListResponse(BaseModel):
    data: list[CmsPost]
    pagination: PaginationMeta


class CmsProject(BaseModel):
    id: str
    title: str
    title_en: str | None = None
    slug: str
    content: dict[str, Any] | None = None
    content_en: dict[str, Any] | None = None
    summary: str | None = None
    cover_image_url: str | None = None
    client_name: str | None = None
    project_date: date_aliased | None = None
    tags: list[str]
    sort_order: int | None = None
    is_featured: bool | None = None
    status: Status2
    published_at: AwareDatetime | None = None
    created_by: str | None = None
    updated_by: str | None = None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class CmsProjectDetailResponse(BaseModel):
    data: CmsProject


class CmsProjectListResponse(BaseModel):
    data: list[CmsProject]
    pagination: PaginationMeta


class CmsReview(BaseModel):
    id: str
    client_name: str
    client_title: str | None = None
    client_company: str | None = None
    client_avatar_url: str | None = None
    testimonial: str | None = None
    rating: Annotated[int, Field(ge=1, le=5)]
    is_featured: bool | None = None
    sort_order: int | None = None
    status: Status2
    published_at: AwareDatetime | None = None
    created_by: str | None = None
    updated_by: str | None = None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class CmsReviewListResponse(BaseModel):
    data: list[CmsReview]
    pagination: PaginationMeta


class CreatePageRequest(BaseModel):
    """
    Content is always created in `draft` state. Use
    `POST /v1/admin/pages/{id}/publish` to transition to `published` —
    this separation enforces the `cms:pages:publish` permission gate.

    """

    title: str
    title_en: str | None = None
    slug: Annotated[
        str | None,
        Field(
            description="URL-friendly slug (auto-generated from title if not provided)"
        ),
    ] = None
    content: dict[str, Any] | None = None
    content_en: dict[str, Any] | None = None
    page_type: PageType
    sort_order: int | None = 0


class CreatePostRequest(BaseModel):
    """
    Content is always created in `draft` state. Use
    `POST /v1/admin/posts/{id}/publish` to transition to `published`.

    """

    title: str
    title_en: str | None = None
    slug: str | None = None
    content: dict[str, Any] | None = None
    content_en: dict[str, Any] | None = None
    excerpt: str | None = None
    cover_image_url: str | None = None
    tags: list[str] | None = None


class CreateProjectRequest(BaseModel):
    """
    Content is always created in `draft` state. Use
    `POST /v1/admin/projects/{id}/publish` to transition to `published`.

    """

    title: str
    title_en: str | None = None
    slug: str | None = None
    content: dict[str, Any] | None = None
    content_en: dict[str, Any] | None = None
    summary: str | None = None
    cover_image_url: str | None = None
    client_name: str | None = None
    project_date: date_aliased | None = None
    tags: list[str] | None = None
    sort_order: int | None = 0
    is_featured: bool | None = False


class CreateReviewRequest(BaseModel):
    """
    Content is always created in `draft` state. Use
    `POST /v1/admin/reviews/{id}/publish` to transition to `published`.

    """

    client_name: str
    client_title: str | None = None
    client_company: str | None = None
    client_avatar_url: str | None = None
    testimonial: str | None = None
    rating: Annotated[int, Field(ge=1, le=5)]
    is_featured: bool | None = False
    sort_order: int | None = 0


class Image(File):
    pass


class Meta(BaseModel):
    title: str | None = None
    description: str | None = None
    image: Image | None = None


class LinkPreviewResponse(BaseModel):
    success: Success
    link: str | None = None
    meta: Meta | None = None


class MarkdownImportRequest(BaseModel):
    markdown: str


class MarkdownImportResponse(BaseModel):
    blocks: list[dict[str, Any]]


class TargetLanguage(StrEnum):
    EN = "en"
    ID = "id"


class TranslateRequest(BaseModel):
    content: Annotated[
        dict[str, Any], Field(description="EditorJS JSON content to translate")
    ]
    target_language: TargetLanguage


class TranslateResponse(BaseModel):
    content: Annotated[
        dict[str, Any], Field(description="Translated EditorJS JSON content")
    ]


class UpdatePageRequest(BaseModel):
    title: str | None = None
    title_en: str | None = None
    slug: str | None = None
    content: dict[str, Any] | None = None
    content_en: dict[str, Any] | None = None
    page_type: PageType | None = None
    sort_order: int | None = None


class UpdatePostRequest(BaseModel):
    title: str | None = None
    title_en: str | None = None
    slug: str | None = None
    content: dict[str, Any] | None = None
    content_en: dict[str, Any] | None = None
    excerpt: str | None = None
    cover_image_url: str | None = None
    tags: list[str] | None = None


class UpdateProjectRequest(BaseModel):
    title: str | None = None
    title_en: str | None = None
    slug: str | None = None
    content: dict[str, Any] | None = None
    content_en: dict[str, Any] | None = None
    summary: str | None = None
    cover_image_url: str | None = None
    client_name: str | None = None
    project_date: date_aliased | None = None
    tags: list[str] | None = None
    sort_order: int | None = None
    is_featured: bool | None = None


class UpdateReviewRequest(BaseModel):
    client_name: str | None = None
    client_title: str | None = None
    client_company: str | None = None
    client_avatar_url: str | None = None
    testimonial: str | None = None
    rating: Annotated[int | None, Field(ge=1, le=5)] = None
    is_featured: bool | None = None
    sort_order: int | None = None


class AdminPermission(StrEnum):
    """
    Fine-grained admin permission identifier, drawn from the RBAC catalog
    (ADR-0017). Dashboards should treat this as a closed enum and refuse to
    render UI for unknown values rather than failing open.

    """

    CMS_PAGES_READ = "cms:pages:read"
    CMS_PAGES_CREATE = "cms:pages:create"
    CMS_PAGES_UPDATE = "cms:pages:update"
    CMS_PAGES_DELETE = "cms:pages:delete"
    CMS_PAGES_PUBLISH = "cms:pages:publish"
    CMS_POSTS_READ = "cms:posts:read"
    CMS_POSTS_CREATE = "cms:posts:create"
    CMS_POSTS_UPDATE = "cms:posts:update"
    CMS_POSTS_DELETE = "cms:posts:delete"
    CMS_POSTS_PUBLISH = "cms:posts:publish"
    CMS_PROJECTS_READ = "cms:projects:read"
    CMS_PROJECTS_CREATE = "cms:projects:create"
    CMS_PROJECTS_UPDATE = "cms:projects:update"
    CMS_PROJECTS_DELETE = "cms:projects:delete"
    CMS_PROJECTS_PUBLISH = "cms:projects:publish"
    CMS_REVIEWS_READ = "cms:reviews:read"
    CMS_REVIEWS_CREATE = "cms:reviews:create"
    CMS_REVIEWS_UPDATE = "cms:reviews:update"
    CMS_REVIEWS_DELETE = "cms:reviews:delete"
    CMS_REVIEWS_PUBLISH = "cms:reviews:publish"
    CMS_FILES_READ = "cms:files:read"
    CMS_FILES_UPLOAD = "cms:files:upload"
    CMS_FILES_UPDATE = "cms:files:update"
    CMS_FILES_DELETE = "cms:files:delete"
    CMS_TOOLS_LINK_PREVIEW = "cms:tools:link_preview"
    CMS_TOOLS_IMPORT_MARKDOWN = "cms:tools:import_markdown"
    CMS_TOOLS_TRANSLATE = "cms:tools:translate"
    CRAWLER_READ = "crawler:read"
    CRAWLER_MANAGE = "crawler:manage"
    CRAWLER_OPERATE = "crawler:operate"
    ADMIN_SESSIONS_REVOKE = "admin:sessions:revoke"


class AdminSessionInfo(BaseModel):
    """
    Session timing fields returned to cookie-authenticated admin callers.
    All timestamps are UTC epoch seconds (int64). Bearer-token callers do not
    receive this object — it is absent (not null) in the response.

    """

    expires_at: Annotated[
        int,
        Field(
            description="UTC epoch seconds when the server-side session expires. The browser\ncookie MaxAge is derived from the same value. The dashboard should\nuse this to schedule a proactive /refresh call before this deadline.\n"
        ),
    ]
    refresh_at: Annotated[
        int,
        Field(
            description="UTC epoch seconds after which a proactive /refresh call is recommended.\nComputed as access-token expiry minus the server's refresh-leeway,\nclamped to a minimum of now+60s to prevent refresh storms from a\nlarge leeway configuration.\n"
        ),
    ]


class AdminMeResponse(BaseModel):
    """
    Identity and authorisation snapshot for the authenticated admin. Returned
    by `/v1/admin/auth/me` so the dashboard can render role-aware UI without
    hand-rolling a session probe against individual protected endpoints.

    """

    sub: Annotated[
        str,
        Field(description="Stable subject identifier from the Authentik access token."),
    ]
    email: Annotated[
        str,
        Field(
            description="Email claim from the verified token. May be an empty string when the\nupstream IdP omits the claim.\n"
        ),
    ]
    permissions: Annotated[
        list[AdminPermission],
        Field(
            description="Deduplicated, alphabetically-sorted permissions resolved from the\ncaller's Authentik group membership. Empty array when no recognised\nrole bundles matched. Stable string enum — see `AdminPermission`.\n"
        ),
    ]
    session: AdminSessionInfo | None = None


class AdminRefreshResponse(BaseModel):
    """
    Identity, authorisation, and updated session timing returned after a
    proactive admin BFF refresh. The `session` object is always present for
    successful refresh responses because `/refresh` is cookie-auth only.

    """

    sub: Annotated[
        str,
        Field(description="Stable subject identifier from the refreshed access token."),
    ]
    email: Annotated[
        str,
        Field(
            description="Email claim from the verified token. May be an empty string when the\nupstream IdP omits the claim.\n"
        ),
    ]
    permissions: Annotated[
        list[AdminPermission],
        Field(
            description="Deduplicated, alphabetically-sorted permissions resolved from the\nrefreshed access token's group membership.\n"
        ),
    ]
    session: AdminSessionInfo


class AdministrasiItem(BaseModel):
    """
    Administrative requirement entry
    """

    type: Annotated[
        str | None, Field(description="Requirement type (requirement or izin_usaha)")
    ] = None
    text: Annotated[
        str | None, Field(description="Requirement text (when type is requirement)")
    ] = None
    data: Annotated[
        list[IzinUsahaItem] | None,
        Field(description="Business license data (when type is izin_usaha)"),
    ] = None


class AMLScreeningResponse(BaseModel):
    screened_name: str | None = None
    screened_type: ScreenedType | None = None
    status: Annotated[
        Status | None,
        Field(
            description="flagged = at least one match with score >= 0.5 found, clear = no matches in all healthy sources, incomplete = no matches but one or more sources failed (cannot guarantee clear)\n"
        ),
    ] = None
    total_matches: int | None = None
    sources: list[AMLSourceResult] | None = None
    screened_at: AwareDatetime | None = None


class AMLEventExport(BaseModel):
    """
    AML event linked to an actor, with event content and regulation references.
    Event content (summary, body_markdown, content_properties) comes from the event_content table (1:1 with events).

    """

    id: Annotated[UUID, Field(description="UUID v7 event identifier")]
    event_type: Annotated[EventType, Field(description="Type of AML event")]
    title: Annotated[
        str | None,
        Field(
            description="Human-readable event title (decision number, sanction name, etc.)"
        ),
    ] = None
    role: Annotated[
        str,
        Field(
            description="Actor's role in the event (defendant, subject, authority, sanctioned, blacklisted, etc.)"
        ),
    ]
    event_date: Annotated[
        date_aliased | None,
        Field(description="Date of the event (ISO 8601 YYYY-MM-DD)"),
    ] = None
    properties: Annotated[
        dict[str, Any] | None,
        Field(description="Type-specific event data (court, authority, etc.)"),
    ] = None
    dataset: Annotated[
        str | None, Field(description="Source dataset for the event")
    ] = None
    source_table: Annotated[
        str | None, Field(description="Fully qualified source table for the event")
    ] = None
    source_id: Annotated[
        str | None, Field(description="ID in the event's source table")
    ] = None
    summary: Annotated[
        str | None, Field(description="Indonesian-language summary (LLM-generated)")
    ] = None
    summary_en: Annotated[
        str | None, Field(description="English-language summary (LLM-generated)")
    ] = None
    body_markdown: Annotated[
        str | None, Field(description="Curated formatted content as markdown")
    ] = None
    content_properties: Annotated[
        dict[str, Any] | None,
        Field(
            description='Type-specific heavy content from event_content.\nVerdicts: {"indictment": {...}, "judicial_considerations": {...}, "sentences": {...}}.\nSanctions: {"reason_detail": "...", "action_description": "..."}.\n'
        ),
    ] = None
    regulations: Annotated[
        list[AMLEventRegulationExport] | None,
        Field(
            description="Regulations linked to this event (legal basis, proven articles, citations)"
        ),
    ] = None


class AgentPosition(BaseModel):
    """
    An agent's position on a specific issue in the deliberation
    """

    issue: Annotated[str, Field(description="The deliberation issue being discussed")]
    stance: PositionStance
    reasoning_summary: Annotated[
        str, Field(description="1-2 sentence summary of the agent's reasoning")
    ]
    round_stated: Annotated[
        int, Field(description="The round number when this position was stated")
    ]


class AgreementMap(BaseModel):
    """
    Tracks agent positions and agreement across deliberation issues
    """

    issues: Annotated[
        dict[str, dict[str, AgentPosition]] | None,
        Field(
            description="Map of issue_key to agent positions (agent_id -> AgentPosition)",
            validate_default=True,
        ),
    ] = {}
    round_count: int | None = 0
    regression_count: int | None = 0
    convergence_score: Annotated[
        float | None,
        Field(description="Proportion of issues with majority agreement (0.0-1.0)"),
    ] = 0.0
    last_convergence_check: Annotated[
        int | None, Field(description="Round number of the last convergence check")
    ] = 0


class BlacklistFiltersResponse(BaseModel):
    subject_type: list[FilterOption]
    case_type: list[FilterOption]
    country: list[FilterOption]
    year_range: YearRange
    defaults: BlacklistDefaults


class NarcoticsDetails(BaseModel):
    """
    Details specific to narcotics cases
    """

    substance: str
    weight_grams: float
    intent: NarcoticsIntent | None = None


class CaseTimeline(BaseModel):
    id: str
    detention_history: list[DetentionEvent]


class ChartData(BaseModel):
    countries: list[ChartItem]
    subject_types: list[ChartItem]
    case_types: list[ChartItem]


class CreateSessionRequest(BaseModel):
    case_summary: Annotated[
        str,
        Field(
            description="Summary of the case for deliberation",
            max_length=10000,
            min_length=50,
        ),
    ]
    case_type: CouncilCaseType | None = None
    structured_data: StructuredCaseData | None = None
    input_type: InputType | None = None


class DefendantDemographics(BaseModel):
    gender_distribution: dict[str, int]
    top_occupations: list[TopOccupation]


class PhaseMetadata(BaseModel):
    """
    Metadata tracking the deliberation phase state
    """

    agreement_map: AgreementMap | None = None
    phase_history: Annotated[
        list[PhaseHistoryItem] | None, Field(validate_default=True)
    ] = []


class SentenceRecommendation(BaseModel):
    """
    Recommendation for sentencing
    """

    imprisonment_months: SentenceRange
    fine_idr: SentenceRange
    additional_penalties: Annotated[
        list[str] | None, Field(description="Additional penalties recommended")
    ] = None


class VerdictRecommendation(BaseModel):
    """
    Recommendation for the verdict
    """

    decision: VerdictDecision
    confidence: Annotated[
        str, Field(description="Confidence level (high, medium, low)")
    ]
    reasoning: Annotated[str, Field(description="Reasoning behind the recommendation")]


class ProcurementAnalytics(BaseModel):
    budget_by_year: list[BudgetByYear]
    budget_by_type: list[BudgetByType]
    top_winners: list[TopWinner]
    competition_metrics: CompetitionMetrics
    competition_health: list[CompetitionHealth] | None = None
    monthly_trends: list[MonthlyTrend] | None = None
    winner_concentration: list[WinnerConcentration] | None = None
    pipeline_status: list[PipelineStatus] | None = None
    budget_efficiency: list[BudgetEfficiency] | None = None
    method_analysis: list[MethodAnalysis] | None = None
    risk_indicators: RiskIndicators | None = None


class SyaratKualifikasi(BaseModel):
    """
    Qualification requirements for the tender
    """

    administrasi: Annotated[
        list[AdministrasiItem] | None, Field(description="Administrative requirements")
    ] = None
    teknis: Annotated[list[str] | None, Field(description="Technical requirements")] = (
        None
    )
    kbki: Annotated[
        list[KBKIItem] | None, Field(description="KBKI classification requirements")
    ] = None


class TenderJadwal(BaseModel):
    """
    Tender schedule stage with history
    """

    no: Annotated[str | None, Field(description="Stage sequence number")] = None
    tahap: Annotated[
        str | None,
        Field(description="Stage name (e.g., Pengumuman, Pendaftaran, Evaluasi)"),
    ] = None
    mulai: Annotated[str | None, Field(description="Start date")] = None
    sampai: Annotated[str | None, Field(description="End date")] = None
    perubahan_count: Annotated[
        int | None, Field(description="Number of schedule changes")
    ] = None
    history: Annotated[
        list[TenderJadwalHistory] | None,
        Field(description="History of schedule changes"),
    ] = None


class TenderRealisasi(BaseModel):
    """
    Contract execution/realization data
    """

    nilai_total_realisasi: Annotated[
        str | None, Field(description="Total realized contract value")
    ] = None
    nilai_pdn: Annotated[
        str | None, Field(description="Domestic component value (Produk Dalam Negeri)")
    ] = None
    nilai_umk: Annotated[
        str | None, Field(description="Small/micro business component value")
    ] = None
    tanggal_selesai: Annotated[str | None, Field(description="Completion date")] = None
    entries: Annotated[
        list[RealisasiEntry] | None,
        Field(description="Individual realization milestones"),
    ] = None


class SPSEAnalyticsSummary(BaseModel):
    total_tenders: Annotated[int, Field(description="Total number of tenders")]
    total_pagu: Annotated[float, Field(description="Total budget ceiling (Nilai Pagu)")]
    total_hps: Annotated[float, Field(description="Total estimated price (Nilai HPS)")]
    avg_peserta: Annotated[
        float, Field(description="Average number of bidders per tender")
    ]
    distinct_instansi: Annotated[
        int, Field(description="Number of distinct institutions")
    ]
    by_jenis_pengadaan: Annotated[
        list[SPSEDistributionItem] | None,
        Field(description="Distribution by procurement type"),
    ] = None


class SPSEDashboardCompetition(BaseModel):
    avg_participants: Annotated[
        float, Field(description="Average participants per tender")
    ]
    participant_distribution: Annotated[
        list[SPSEDashboardDistributionItem],
        Field(description="Distribution by participant count buckets"),
    ]
    single_bidder_rate: Annotated[
        float, Field(description="Percentage of tenders with single bidder")
    ]
    participant_distribution_conclusion: Annotated[
        str, Field(description="Conclusion about participant distribution")
    ]


class SPSEDashboardEfficiency(BaseModel):
    avg_duration_days: Annotated[
        float, Field(description="Average tender duration in days")
    ]
    duration_distribution: Annotated[
        list[SPSEDashboardDistributionItem],
        Field(description="Distribution by duration buckets (0-30, 31-60, etc.)"),
    ]
    duration_distribution_conclusion: Annotated[
        str, Field(description="Conclusion about duration distribution")
    ]
    tender_result_distribution: Annotated[
        list[SPSEDashboardDistributionItem],
        Field(description="Distribution by tender result (batal/gagal/selesai)"),
    ]
    tender_result_conclusion: Annotated[
        str, Field(description="Conclusion about tender results")
    ]


class SPSEDashboardMarketOpportunity(BaseModel):
    value_distribution: Annotated[
        list[SPSEDashboardDistributionItem],
        Field(description="Distribution by value buckets (<500M, 500M-2.5B, etc.)"),
    ]
    value_distribution_conclusion: Annotated[
        str, Field(description="Conclusion about value distribution")
    ]
    procurement_type_count_distribution: Annotated[
        list[SPSEDashboardDistributionItem],
        Field(description="Distribution by procurement type (percentage by count)"),
    ]
    procurement_type_count_conclusion: Annotated[
        str, Field(description="Conclusion about procurement type count distribution")
    ]
    procurement_type_value_distribution: Annotated[
        list[SPSEDashboardDistributionItem],
        Field(description="Distribution by procurement type (percentage by value)"),
    ]
    procurement_type_value_conclusion: Annotated[
        str, Field(description="Conclusion about procurement type value distribution")
    ]


class SPSEDashboardValueForMoney(BaseModel):
    avg_savings_rate: Annotated[
        float, Field(description="Average savings percentage from HPS")
    ]
    total_potential_savings: Annotated[
        float, Field(description="Total potential savings in IDR")
    ]
    savings_distribution: Annotated[
        list[SPSEDashboardDistributionItem],
        Field(description="Distribution by savings percentage buckets"),
    ]
    savings_distribution_conclusion: Annotated[
        str, Field(description="Conclusion about savings distribution")
    ]


class ScreeningEntitySanction(BaseModel):
    sanctions_list: ScreeningSanctionsList
    list_entry_id: str | None = None
    listed_at: date_aliased | None = None
    delisted_at: date_aliased | None = None


class SearchResponse(BaseModel):
    data: list[SearchResult]
    meta: PaginationMeta
    summary: SearchSummary | None = None


class StreamEventData(BaseModel):
    """
    Data payload for streaming events (SSE)
    """

    event_type: StreamEventType | None = None
    agent_id: AgentId | None = None
    content: Annotated[
        str | None, Field(description="Event content (chunk text or message)")
    ] = None
    message_id: Annotated[str | None, Field(description="Message identifier")] = None
    full_content: Annotated[
        str | None, Field(description="Full message content (only on agent_complete)")
    ] = None


class AMLActorExport(BaseModel):
    """
    Complete AML actor profile with nested events, names, identifiers, links, and regulations.
    Mirrors the entity_graph schema for ProcureLens consumption.

    """

    id: Annotated[UUID, Field(description="UUID v7 actor identifier")]
    actor_type: Annotated[ActorType, Field(description="Type of actor")]
    canonical_name: Annotated[str, Field(description="Primary name of the actor")]
    name_normalized: Annotated[
        str,
        Field(
            description="Normalized name for matching (lowercased, whitespace-trimmed)"
        ),
    ]
    properties: Annotated[
        dict[str, Any] | None,
        Field(
            description="Flexible actor-specific data (e.g., nationality, date_of_birth)"
        ),
    ] = None
    dataset: Annotated[
        str, Field(description="Source dataset (interpol, lkpp, spse, mahkamah, etc.)")
    ]
    source_table: Annotated[
        str | None,
        Field(
            description="Fully qualified source table (e.g., crawler.interpol_red_notices)"
        ),
    ] = None
    source_id: Annotated[str | None, Field(description="ID in source table")] = None
    names: Annotated[
        list[AMLNameExport] | None, Field(description="Name variants for the actor")
    ] = None
    identifiers: Annotated[
        list[AMLIdentifierExport] | None,
        Field(description="External registry IDs (passport, npwp, lkpp_id, etc.)"),
    ] = None
    events: Annotated[
        list[AMLEventExport] | None,
        Field(
            description="AML events (verdicts, sanctions, blacklist entries) with content and regulations"
        ),
    ] = None
    links: Annotated[
        list[AMLLinkExport] | None,
        Field(
            description="Actor-to-actor relationships (ownership, directorship, etc.)"
        ),
    ] = None
    regulations: Annotated[
        list[AMLActorRegulationExport] | None,
        Field(description="Regulations linked to this actor (issuer, enforcer roles)"),
    ] = None
    first_seen: Annotated[
        AwareDatetime | None,
        Field(description="When crawler first observed this entity"),
    ] = None
    last_seen: Annotated[
        AwareDatetime | None,
        Field(description="When crawler last observed this entity"),
    ] = None
    updated_at: Annotated[
        AwareDatetime | None,
        Field(description="Last update timestamp (used for cursor-based pagination)"),
    ] = None


class ParsedCaseInput(BaseModel):
    """
    Parsed and structured case information
    """

    case_type: CouncilCaseType
    summary: str
    defendant_profile: CouncilDefendantProfile | None = None
    key_facts: list[str] | None = []
    charges: list[str] | None = []
    narcotics: NarcoticsDetails | None = None
    corruption: CorruptionDetails | None = None


class DeliberationMessage(BaseModel):
    """
    A message in a deliberation session
    """

    id: str
    session_id: str
    sender: Annotated[
        UserSender | AgentSender | SystemSender,
        Field(description="Union type for message senders", discriminator="type"),
    ]
    content: str
    intent: str | None = None
    cited_cases: list[str] | None = []
    cited_laws: list[str] | None = []
    timestamp: AwareDatetime | None = None


class CreateSessionResponse(BaseModel):
    """
    Response after creating a session
    """

    session_id: str
    parsed_case: ParsedCaseInput
    similar_cases: list[CouncilSimilarCase]
    initial_message: DeliberationMessage | None = None


class CreateSessionStreamEventData(BaseModel):
    """
    Data payload for streaming session creation events (SSE)
    """

    event_type: CreateSessionStreamEventType
    status: Annotated[
        str | None, Field(description="Progress status for setup events")
    ] = None
    session_id: Annotated[
        str | None,
        Field(description="Session identifier once the session has been created"),
    ] = None
    parsed_case: ParsedCaseInput | None = None
    similar_cases: list[CouncilSimilarCase] | None = None
    agent_id: AgentId | None = None
    content: Annotated[
        str | None, Field(description="Event content, chunk text, or error text")
    ] = None
    message_id: Annotated[
        str | None, Field(description="Message identifier for agent stream events")
    ] = None
    full_content: Annotated[
        str | None, Field(description="Full message content on agent completion")
    ] = None
    initial_message: DeliberationMessage | None = None
    status_code: Annotated[
        int | None, Field(description="HTTP-like status code for terminal error events")
    ] = None


class LegalOpinionDraft(BaseModel):
    """
    Generated legal opinion from a deliberation session
    """

    session_id: Annotated[str, Field(description="Session this opinion belongs to")]
    generated_at: Annotated[
        AwareDatetime, Field(description="When the opinion was generated")
    ]
    case_summary: Annotated[str, Field(description="Summary of the case")]
    verdict_recommendation: VerdictRecommendation
    sentence_recommendation: SentenceRecommendation
    legal_arguments: LegalArguments
    cited_precedents: Annotated[
        list[CitedPrecedent] | None,
        Field(description="Precedent cases cited in the opinion"),
    ] = None
    applicable_laws: Annotated[
        list[ApplicableLaw] | None, Field(description="Laws applicable to the case")
    ] = None
    dissenting_views: Annotated[
        list[str] | None, Field(description="Dissenting opinions from judges")
    ] = None


class GetMessagesResponse(BaseModel):
    """
    Response for getting messages
    """

    messages: list[DeliberationMessage]


class ProcurementDetail(BaseModel):
    id: int
    kode_tender: str
    nama_tender: str
    tender_type: str | None = None
    instansi: str | None = None
    satuan_kerja: str | None = None
    jenis_pengadaan: str | None = None
    metode_pengadaan: str | None = None
    tahun_anggaran: str | None = None
    nilai_pagu: str | None = None
    nilai_hps: str | None = None
    jenis_kontrak: str | None = None
    tanggal_pembuatan: date_aliased | None = None
    tahap_saat_ini: str | None = None
    peserta_count: int | None = None
    source_url: str | None = None
    lpse_code: str | None = None
    lokasi_pekerjaan: Annotated[
        list[str] | None, Field(description="Work locations")
    ] = None
    peserta: Annotated[
        list[TenderPeserta] | None, Field(description="Tender participants")
    ] = None
    hasil_evaluasi: Annotated[
        list[TenderHasilEvaluasi] | None, Field(description="Evaluation results")
    ] = None
    pemenang: Annotated[
        list[TenderPemenang] | None, Field(description="Tender winners")
    ] = None
    pemenang_berkontrak: Annotated[
        list[TenderPemenang] | None, Field(description="Contracted winners")
    ] = None
    blacklist_matches: list[BlacklistMatch] | None = None
    uraian_pdf_url: Annotated[
        str | None, Field(description="Source URL of the Uraian Singkat Pekerjaan PDF")
    ] = None
    uraian_pdf_download_url: Annotated[
        str | None,
        Field(
            description="Pre-signed URL for downloading the Uraian PDF (expires in 1 hour)"
        ),
    ] = None
    jadwal: Annotated[
        list[TenderJadwal] | None, Field(description="Schedule stages with history")
    ] = None
    kualifikasi_usaha: Annotated[
        str | None,
        Field(
            description="Business qualification class (Non Kecil, Kecil, or Koperasi)"
        ),
    ] = None
    syarat_kualifikasi: SyaratKualifikasi | None = None
    realisasi: TenderRealisasi | None = None
    alasan_pembatalan: Annotated[
        str | None,
        Field(description="Cancellation reason for failed/cancelled tenders"),
    ] = None
    status_paket: Annotated[
        str | None,
        Field(description="Package status badge (Paket Gagal, Paket Dibatalkan, etc.)"),
    ] = None
    oap_khusus: Annotated[
        bool | None,
        Field(description="Reserved for Orang Asli Papua (Papua affirmative action)"),
    ] = None
    tipe_pelaksana_swakelola: Annotated[
        str | None,
        Field(description="Swakelola executor type for self-managed procurement"),
    ] = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class SPSEDashboardAnalytics(BaseModel):
    lang: Annotated[Lang, Field(description="Response language")]
    summary: SPSEDashboardSummary
    market_opportunity: SPSEDashboardMarketOpportunity
    competition: SPSEDashboardCompetition
    efficiency: SPSEDashboardEfficiency
    value_for_money: SPSEDashboardValueForMoney


class ScreeningEntityDetail(BaseModel):
    id: UUID
    entity_type: EntityType1
    topics: list[str]
    remarks: str | None = None
    names: list[ScreeningEntityName]
    sanctions: list[ScreeningEntitySanction]


class ScreeningEntityResponse(BaseModel):
    entity: ScreeningEntityDetail


class SendMessageResponse(BaseModel):
    user_message: DeliberationMessage
    agent_responses: list[DeliberationMessage]


class CaseInput(BaseModel):
    """
    Complete case input with raw and parsed data
    """

    input_type: InputType
    raw_input: str
    parsed_case: ParsedCaseInput


class ContinueDiscussionResponse(BaseModel):
    new_messages: list[DeliberationMessage]
    total_messages: int


class DeliberationSession(BaseModel):
    """
    A deliberation session
    """

    id: str
    user_id: str | None = None
    status: SessionStatus
    current_phase: DeliberationPhase | None = None
    phase_metadata: PhaseMetadata | None = None
    case_input: CaseInput
    similar_cases: Annotated[
        list[CouncilSimilarCase] | None, Field(validate_default=True)
    ] = []
    messages: Annotated[
        list[DeliberationMessage] | None, Field(validate_default=True)
    ] = []
    legal_opinion: dict[str, Any] | None = None
    structured_summary: Annotated[
        dict[str, Any] | None,
        Field(
            description="Structured deliberation summary (populated in summary phase)"
        ),
    ] = None
    created_at: AwareDatetime
    updated_at: AwareDatetime
    concluded_at: AwareDatetime | None = None


class GenerateOpinionResponse(BaseModel):
    """
    Response containing the generated legal opinion
    """

    opinion: LegalOpinionDraft


class GetSessionResponse(BaseModel):
    """
    Response for getting a session
    """

    session: DeliberationSession


class ListSessionsResponse(BaseModel):
    """
    Response for listing sessions
    """

    sessions: list[DeliberationSession]
    pagination: dict[str, int]
